# Notes:  expirationTime is a tuple (beforeMinutes, afterMinutes)
#         hazardConflictList is a list of hazard types which conflict with the
#                            given hazard type.
#         hazardHatchArea represents the area type that a hazard geometry will
#                         be translated into when the hazard is issued. For example,
#                         A WS.W polygon will be translated into a collection of
#                         zones in the associated WSW when issued. 
#                         An FA.A will be translated into a 
#                         collection of counties in the associated FFA when issued.
#                         Some possible values include: county, zone, polygon. 
#                         These are the names of the corresponding tables
#                         in the maps db.
#                         Polygon is used when the polygon will represent the
#                         warned area in the associated product, as is the case
#                         with a TO.W. 
#         hazardHatchLabel The label field to associate with the hazardHatchArea. 
#                          This corresponds to the label field associated with
#                          the maps db table which backs the hatch area. If
#                          hatch area is Polygon, then label field does not apply.
HazardTypes = {
    'AF.Y' : {'headline': 'ASHFALL ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['AF.W'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'AQ.Y' : {'headline': 'AIR QUALITY ALERT',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['AS.O', 'AS.Y'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'AS.O' : {'headline': 'AIR STAGNATION OUTLOOK',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['AQ.Y', 'AS.Y'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'AS.Y' : {'headline': 'AIR STAGNATION ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['AQ.Y', 'AS.O'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'BW.Y' : {'headline': 'BRISK WIND ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['GL.W', 'SR.W', 'HF.W', 'TR.A', 'TR.W', 'HU.A', 'HU.W', 'HU.S', 'SC.Y', 'SW.Y', 'SE.W', 'RB.Y', 'SI.Y'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'BZ.A' : {'headline' : 'BLIZZARD WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['LE.A', 'WS.A', 'BZ.W', 'IS.W', 'LE.W', 'WS.W', 'WW.Y', 'LE.Y', 'ZR.Y'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'BZ.W' : {'headline' : 'BLIZZARD WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['BZ.A', 'LE.A', 'WS.A', 'IS.W', 'LE.W', 'WS.W', 'WW.Y', 'LE.Y', 'ZR.Y'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'CF.A' : {'headline': 'COASTAL FLOOD WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['CF.W', 'CF.Y', 'HU.A', 'TR.A', 'TY.A', 'HU.W', 'TR.W'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'CF.W' : {'headline': 'COASTAL FLOOD WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['CF.A', 'CF.Y', 'HU.W', 'TR.W', 'TY.W'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'CF.Y' : {'headline': 'COASTAL FLOOD ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['CF.W', 'CF.A', 'HU.W', 'TR.W', 'TY.W'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'CF.S' : {'headline': '',   # No headline for this VTEC
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['HU.A', 'TR.A', 'TY.A', 'CF.Y', 'CF.W', 'CF.A'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'DS.W' : {'headline': 'DUST STORM WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['DU.Y'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'DU.Y' : {'headline': 'BLOWING DUST ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['DS.W'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'EC.A' : {'headline': 'EXTREME COLD WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['WC.A', 'EC.W', 'WC.W'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'EC.W' : {'headline': 'EXTREME COLD WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['EC.A', 'WC.A', 'WC.W', 'WC.Y'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'EH.A' : {'headline': 'EXCESSIVE HEAT WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['EH.W', 'HT.Y'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'EH.W' : {'headline': 'EXCESSIVE HEAT WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['EH.A', 'HT.Y'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'EW.W' : {'headline': 'EXCESSIVE WIND WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['EH.A', 'HT.Y'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'FA.A' : {'headline': 'AREAL FLOOD WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['FF.A'],
              'hazardHatchArea': 'county',
              'hazardHatchLabel': 'countyName',
              'replacedBy': ['FA.W', 'FA.Y'],
              },
    'FA.W' : {'headline': 'AREAL FLOOD WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['FA.Y'],
              'hazardHatchArea': 'county',
              'hazardHatchLabel': 'countyName',
              'replacedBy': ['FA.Y'],
              },
    'FA.Y' : {'headline': 'AREAL FLOOD ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['FA.W'],
              'hazardHatchArea': 'county',
              'hazardHatchLabel': 'countyName',
              'replacedBy': ['FA.W'],
              },
    'FF.A' : {'headline': 'FLASH FLOOD WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['FA.A'],
              'hazardHatchArea': 'county',
              'hazardHatchLabel': 'countyName',
              'replacedBy': ['FF.W.Convective', 'FF.W.NonConvective'],
              },
    'FF.W.Convective' : {
              'headline': 'FLASH FLOOD WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-10, 10),
              'hazardConflictList': [],
              'hazardHatchArea': 'polygon',
              'hazardHatchLabel': '',

              },
    'FF.W.NonConvective' : {
              'headline': 'FLASH FLOOD WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-10, 10),
              'hazardConflictList': [],
              'hazardHatchArea': 'polygon',
              'hazardHatchLabel': '',
              },
    'FG.Y' : {'headline': 'DENSE FOG ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'FL.A' : {'headline': 'FLOOD WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'hazardHatchArea': 'county',
              'hazardHatchLabel': 'countyName',
              'replacedBy': ['FL.W', 'FL.Y'],
              },
    'FL.W' : {'headline': 'FLOOD WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'hazardHatchArea': 'county',
              'hazardHatchLabel': 'countyName',
              'replacedBy': ['FL.Y'],
              },
    'FL.Y' : {'headline': 'FLOOD ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'hazardHatchArea': 'county',
              'hazardHatchLabel': 'countyName',
              'replacedBy': ['FL.W'],
              },
    'FR.Y' : {'headline': 'FROST ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['FZ.A', 'FZ.W', 'HZ.W', 'HZ.A'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'FW.A' : {'headline': 'FIRE WEATHER WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['FW.W'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'FW.W' : {'headline': 'RED FLAG WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['FW.A'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'FZ.A' : {'headline': 'FREEZE WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['FZ.W', 'FR.Y', 'HZ.W', 'HZ.A'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'FZ.W' : {'headline': 'FREEZE WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['FZ.A', 'FR.Y', 'HZ.W', 'HZ.A'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'GL.A' : {'headline': 'GALE WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['SR.W', 'HF.W', 'BW.Y', 'TR.A', 'TR.W', 'HU.A', 'HU.W', 'SC.Y', 'SW.Y', 'SE.W', 'RB.Y', 'SI.Y', 'GL.W', 'SR.A', 'HF.A', 'SE.A', 'TY.A', 'TY.W'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'GL.W' : {'headline': 'GALE WARNING',            
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['SR.W', 'HF.W', 'BW.Y', 'TR.W', 'HU.W', 'SC.Y', 'SW.Y', 'SE.W', 'RB.Y', 'SI.Y', 'GL.A', 'SR.A', 'SE.A', 'TY.W'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'HF.A' : {'headline': 'HURRICANE FORCE WIND WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['BW.Y', 'TR.A', 'TR.W', 'HU.A', 'HU.W', 'GL.A', 'SR.A', 'HF.W', 'SE.A', 'TY.A', 'TY.W'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'HF.W' : {'headline': 'HURRICANE FORCE WIND WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['GL.W', 'SR.W', 'BW.Y', 'TR.A', 'TR.W', 'HU.A', 'HU.W', 'SC.Y', 'SW.Y', 'SE.W', 'RB.Y', 'SI.Y', 'GL.A', 'SR.A', 'HF.A', 'SE.A', 'TY.W'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'HI.A' : {'headline': 'HURRICANE WIND WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['GL.W', 'SR.W', 'BW.Y', 'TR.A', 'TR.W', 'HU.A', 'HU.W', 'SC.Y', 'SW.Y', 'SE.W', 'RB.Y', 'SI.Y', 'GL.A', 'SR.A', 'HF.A', 'SE.A', 'TY.W'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'HI.W' : {'headline': 'HURRICANE WIND WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['GL.W', 'SR.W', 'BW.Y', 'TR.A', 'TR.W', 'HU.A', 'HU.W', 'SC.Y', 'SW.Y', 'SE.W', 'RB.Y', 'SI.Y', 'GL.A', 'SR.A', 'HF.A', 'SE.A', 'TY.W'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'HT.Y' : {'headline': 'HEAT ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['EH.A', 'EH.W'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'HU.A' : {'headline': 'HURRICANE WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['HF.W', 'BW.Y', 'TR.A', 'HU.W', 'HU.S', 'GL.A', 'SR.A', 'HF.A', 'SE.A', 'CF.S', 'CF.A'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'HU.S' : {'headline': '',  # No headline for this VTEC
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['TR.A', 'TR.W', 'HU.A', 'HU.W', 'TY.A', 'TY.W'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'HU.W' : {'headline': 'HURRICANE WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['GL.W', 'SR.W', 'HF.W', 'BW.Y', 'TR.A', 'TR.W', 'HU.A', 'SC.Y', 'SW.Y', 'SE.W', 'RB.Y', 'SI.Y', 'GL.A', 'SR.A', 'HF.A', 'SE.A', 'HU.S', 'CF.W', 'CF.A', 'CF.Y', 'CF.S', 'SU.W', 'SU.Y'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'HW.A' : {'headline': 'HIGH WIND WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['HW.W', 'WI.Y'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'HW.W' : {'headline': 'HIGH WIND WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['HW.A', 'LW.Y', 'WI.Y'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'HY.O' : {'headline': 'HYDROLOGIC OUTLOOK',  
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': False,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['HW.A', 'LW.Y', 'WI.Y'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'HY.S' : {'headline': '',  # No headline for this VTEC
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': False,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['HW.A', 'LW.Y', 'WI.Y'],
              'hazardHatchArea': 'county',
              'replacedBy': ['FL.A'],
              },
    'HZ.A' : {'headline': 'HARD FREEZE WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['FZ.W', 'FR.Y', 'FZ.A', 'HZ.W'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'HZ.W' : {'headline': 'HARD FREEZE WARNING',  
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['FZ.A', 'FR.Y', 'HZ.A', 'FZ.W'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'IS.W' : {'headline': 'ICE STORM WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['BZ.A', 'LE.A', 'WS.A', 'BZ.W', 'WS.W', 'LE.W', 'WW.Y', 'LE.Y', 'ZR.Y'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'LE.A' : {'headline': 'LAKE EFFECT SNOW WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['BZ.A', 'WS.A', 'BZ.W', 'IS.W', 'WS.W', 'LE.W', 'WW.Y', 'LE.Y', 'ZR.Y'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'LE.W' : {'headline': 'LAKE EFFECT SNOW WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['BZ.A', 'LE.A', 'WS.A', 'BZ.W', 'IS.W', 'WS.W', 'WW.Y', 'LE.Y', 'ZR.Y'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'LE.Y' : {'headline': 'LAKE EFFECT SNOW ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['BZ.A', 'LE.A', 'WS.A', 'BZ.W', 'IS.W', 'LE.W', 'WS.W', 'WW.Y', 'ZR.Y'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'LO.Y' : {'headline': 'LOW WATER ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'LS.A' : {'headline': 'LAKESHORE FLOOD WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['LS.W', 'LS.Y', 'LS.S'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'LS.S' : {'headline': '',  # No headline for this VTEC
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['LS.A', 'LS.Y', 'LS.W'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'LS.W' : {'headline': 'LAKESHORE FLOOD WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['LS.A', 'LS.Y', 'LS.S'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'LS.Y' : {'headline': 'LAKESHORE FLOOD ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['LS.A', 'LS.W', 'LS.S'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'LW.Y' : {'headline': 'LAKE WIND ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['HW.W', 'WI.Y'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'MA.S' : {'headline': '',  # No headline for this VTEC
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'MA.W' : {'headline': 'SPECIAL MARINE WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': False,
              'expirationTime': (-10, 10),
              'hazardConflictList': [],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'MF.Y' : {'headline': 'DENSE FOG ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              }, # Marine Fog
    'MH.Y' : {'headline': 'ASHFALL ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['MH.W'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              }, # Marine Ashfall
    'MS.Y' : {'headline': 'DENSE SMOKE ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              }, # Marine Smoke
    'RB.Y' : {'headline': 'SMALL CRAFT ADVISORY FOR ROUGH BAR',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['GL.W', 'SR.W', 'HF.W', 'BW.Y', 'TR.W', 'HU.W', 'SE.W', 'GL.A', 'SR.A', 'SE.A', 'TY.W'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'SC.Y' : {'headline': 'SMALL CRAFT ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['GL.W', 'SR.W', 'SR.A', 'BW.Y', 'TR.W', 'HU.W', 'SE.W', 'SE.A', 'HF.W', 'GL.A', 'TY.W'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'SE.A' : {'headline': 'HAZARDOUS SEAS WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['SR.W', 'HF.W', 'HF.A', 'BW.Y', 'TR.A', 'TR.W', 'HU.A', 'HU.W', 'SC.Y', 'SW.Y', 'RB.Y', 'SI.Y', 'GL.A', 'GL.W', 'SE.W', 'SR.A', 'TY.A', 'TY.W'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'SE.W' : {'headline': 'HAZARDOUS SEAS WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['SR.W', 'HF.W', 'BW.Y', 'TR.W', 'HU.W', 'TY.W', 'SC.Y', 'SW.Y', 'RB.Y', 'SI.Y', 'GL.A', 'GL.W', 'SE.A', 'SR.A'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'SI.Y' : {'headline': 'SMALL CRAFT ADVISORY FOR WINDS',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['SR.W', 'SR.A', 'BW.Y', 'TR.W', 'HU.W', 'TY.W', 'GL.W', 'GL.A', 'HF.W', 'SE.A', 'SE.W'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'SM.Y' : {'headline': 'DENSE SMOKE ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'SR.A' : {'headline': 'STORM WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['GL.A', 'GL.W', 'HF.A', 'HF.W', 'HU.W', 'HU.A', 'TR.W', 'TR.A', 'RB.Y', 'SC.Y', 'SE.A', 'SE.W', 'SI.Y', 'SR.W', 'SW.Y', 'TY.W', 'TY.A'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'SR.W' : {'headline': 'STORM WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['GL.W', 'HF.W', 'BW.Y', 'TR.W', 'HU.W', 'TY.W', 'SC.Y', 'SW.Y', 'SE.W', 'SE.A', 'RB.Y', 'SI.Y', 'GL.A', 'SR.A'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'SU.W' : {'headline': 'HIGH SURF WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['SU.Y', 'HU.W', 'TR.W', 'TY.W'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'SU.Y' : {'headline': 'HIGH SURF ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['SU.W', 'HU.W', 'TR.W', 'TY.W'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },             
    'SV.A' : {'headline': 'SEVERE THUNDERSTORM WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['TO.A'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'SV.W' : {'headline': 'SEVERE THUNDERSTORM WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': False,
              'expirationTime': (-10, 10),
              'hazardConflictList': [],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'SW.Y' : {'headline': 'SMALL CRAFT ADVISORY FOR HAZARDOUS SEAS',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['GL.W', 'SR.W', 'HF.W', 'BW.Y', 'TR.W', 'HU.W', 'TY.W', 'SE.W', 'GL.A', 'SR.A', 'SE.A'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'TI.A' : {'headline': 'TROPICAL STORM WIND WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['GL.W', 'SR.W', 'HF.W', 'BW.Y', 'TR.W', 'HU.W', 'TY.W', 'SE.W', 'GL.A', 'SR.A', 'SE.A'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'TI.W' : {'headline': 'TROPICAL STORM WIND WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['GL.W', 'SR.W', 'HF.W', 'BW.Y', 'TR.W', 'HU.W', 'TY.W', 'SE.W', 'GL.A', 'SR.A', 'SE.A'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'TO.A' : {'headline': 'TORNADO WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['SV.A'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'TO.W' : {'headline': 'TORNADO WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': False,
              'expirationTime': (-10, 10),
              'hazardConflictList': [],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'TR.A' : {'headline': 'TROPICAL STORM WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['HF.W', 'TR.W', 'HU.A', 'HU.S', 'HU.W', 'TY.A', 'TY.W', 'GL.A', 'SR.A', 'HF.A', 'SE.A', 'CF.A', 'CF.S'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'TR.W' : {'headline': 'TROPICAL STORM WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['GL.W', 'SR.W', 'HF.W', 'BW.Y', 'TR.A', 'HU.W', 'HU.S', 'SC.Y', 'SW.Y', 'SE.W', 'RB.Y', 'SI.Y', 'CF.S', 'TY.W', 'GL.A', 'SR.A', 'HF.A', 'SE.A', 'CF.W', 'CF.A', 'CF.Y', 'SU.W', 'SU.Y'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'TS.A' : {'headline': 'TSUNAMI WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['TS.W'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'TS.W' : {'headline': 'TSUNAMI WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': False,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['TS.A'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'TY.A' : {'headline': 'TYPHOON WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['TR.A', 'TY.W', 'HU.S', 'HF.W', 'GL.A', 'SR.A', 'HF.A', 'SE.A', 'CF.A', 'CF.S'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'TY.W' : {'headline': 'TYPHOON WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['TY.A', 'HU.S', 'TR.A', 'TR.W', 'GL.A', 'SR.A', 'HF.A', 'SE.A', 'CF.A', 'CF.S', 'SU.Y', 'GL.W', 'SR.W', 'HF.W', 'BW.Y', 'SC.Y', 'SW.Y', 'SE.W', 'RB.Y', 'SI.Y', 'CF.W', 'CF.Y', 'SU.W'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'UP.A' : {'headline': 'HEAVY FREEZING SPRAY WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['TY.A', 'HU.S', 'TR.A', 'TR.W', 'GL.A', 'SR.A', 'HF.A', 'SE.A', 'CF.A', 'CF.S', 'SU.Y', 'GL.W', 'SR.W', 'HF.W', 'BW.Y', 'SC.Y', 'SW.Y', 'SE.W', 'RB.Y', 'SI.Y', 'CF.W', 'CF.Y', 'SU.W'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'UP.W' : {'headline': 'HEAVY FREEZING SPRAY WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['TR.A', 'TR.W', 'HU.A', 'HU.S', 'HU.W', 'UP.Y'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'UP.Y' : {'headline': 'FREEZING SPRAY ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['TR.A', 'TR.W', 'HU.A', 'HU.S', 'HU.W', 'UP.W'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'WC.A' : {'headline': 'WIND CHILL WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['WC.Y', 'WC.W'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'WC.W' : {'headline': 'WIND CHILL WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['WC.A', 'WC.Y'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'WC.Y' : {'headline': 'WIND CHILL ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['WC.A', 'WC.W'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'WI.Y' : {'headline': 'WIND ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['HW.A', 'HW.W', 'LW.Y'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
             },
    'WS.A' : {'headline': 'WINTER STORM WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['BZ.A', 'LE.A', 'BZ.W', 'IS.W', 'WS.W', 'LE.W', 'WW.Y', 'LE.Y', 'ZR.Y'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'WS.W' : {'headline': 'WINTER STORM WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['BZ.A', 'LE.A', 'WS.A', 'BZ.W', 'IS.W', 'LE.W', 'WW.Y', 'LE.Y', 'ZR.Y'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'WW.Y' : {'headline': 'WINTER WEATHER ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['BZ.A', 'LE.A', 'WS.A', 'BZ.W', 'IS.W', 'WS.W', 'LE.W', 'LE.Y', 'ZR.Y'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'ZF.Y' : {'headline': 'FREEZING FOG ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              },
    'ZR.Y' : {'headline': 'FREEZING RAIN ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['BZ.A', 'LE.A', 'WS.A', 'BZ.W', 'IS.W', 'WS.W', 'LE.W', 'WW.Y', 'LE.Y'],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
             },
    }
