# Note:  expirationTime is a tuple (beforeMinutes, afterMinutes)
HazardTypes = {
    'AF.Y' : {'headline': 'ASHFALL ADVISORY',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'AQ.Y' : {'headline': 'AIR QUALITY ALERT',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'AS.O' : {'headline': 'AIR STAGNATION OUTLOOK',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'AS.Y' : {'headline': 'AIR STAGNATION ADVISORY',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'BW.Y' : {'headline': 'BRISK WIND ADVISORY',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'BZ.A' : {'headline' : 'BLIZZARD WATCH',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'BZ.W' : {'headline' : 'BLIZZARD WARNING',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'CF.A' : {'headline': 'COASTAL FLOOD WATCH',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'CF.W' : {'headline': 'COASTAL FLOOD WARNING',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'CF.Y' : {'headline': 'COASTAL FLOOD ADVISORY',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'CF.S' : {'headline': '',   # No headline for this VTEC
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'DS.W' : {'headline': 'DUST STORM WARNING',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'DU.Y' : {'headline': 'BLOWING DUST ADVISORY',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'EC.A' : {'headline': 'EXTREME COLD WATCH',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'EC.W' : {'headline': 'EXTREME COLD WARNING',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'EH.A' : {'headline': 'EXCESSIVE HEAT WATCH',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'EH.W' : {'headline': 'EXCESSIVE HEAT WARNING',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'EW.W' : {'headline': 'EXCESSIVE WIND WARNING',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'FA.A' : {'headline': 'AREAL FLOOD WATCH',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'FA.W' : {'headline': 'AREAL FLOOD WARNING',
              'overrideLock':'True',
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'FA.Y' : {'headline': 'AREAL FLOOD ADVISORY',
              'overrideLock':'True',
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'FF.A' : {'headline': 'FLASH FLOOD WATCH',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'FF.W.Convective' : {
              'headline': 'FLASH FLOOD WARNING',
              'overrideLock':'True',
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-10, 10)
              },
    'FF.W.NonConvective' : {
              'headline': 'FLASH FLOOD WARNING',
              'overrideLock':'True',
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-10, 10)
              },
    'FG.Y' : {'headline': 'DENSE FOG ADVISORY',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'FL.A' : {'headline': 'FLOOD WATCH',
              'overrideLock':'True',
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'FL.W' : {'headline': 'FLOOD WARNING',
              'overrideLock':'True',
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'FL.Y' : {'headline': 'FLOOD ADVISORY',
              'overrideLock':'True',
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'FR.Y' : {'headline': 'FROST ADVISORY',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'FW.A' : {'headline': 'FIRE WEATHER WATCH',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'FW.W' : {'headline': 'RED FLAG WARNING',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'FZ.A' : {'headline': 'FREEZE WATCH',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'FZ.W' : {'headline': 'FREEZE WARNING',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'GL.A' : {'headline': 'GALE WATCH',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'GL.W' : {'headline': 'GALE WARNING',            
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'HF.A' : {'headline': 'HURRICANE FORCE WIND WATCH',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'HF.W' : {'headline': 'HURRICANE FORCE WIND WARNING',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'HI.A' : {'headline': 'HURRICANE WIND WATCH',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'HI.W' : {'headline': 'HURRICANE WIND WARNING',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'HT.Y' : {'headline': 'HEAT ADVISORY',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'HU.A' : {'headline': 'HURRICANE WATCH',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'HU.S' : {'headline': '',  # No headline for this VTEC
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'HU.W' : {'headline': 'HURRICANE WARNING',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'HW.A' : {'headline': 'HIGH WIND WATCH',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'HW.W' : {'headline': 'HIGH WIND WARNING',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'HY.S' : {'headline': '',  # No headline for this VTEC
              'overrideLock':'True',
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': False,
              'expirationTime': (-30, 30)
              },
    'HZ.A' : {'headline': 'HARD FREEZE WATCH',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'HZ.W' : {'headline': 'HARD FREEZE WARNING',  
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'IS.W' : {'headline': 'ICE STORM WARNING',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'LE.A' : {'headline': 'LAKE EFFECT SNOW WATCH',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'LE.W' : {'headline': 'LAKE EFFECT SNOW WARNING',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'LE.Y' : {'headline': 'LAKE EFFECT SNOW ADVISORY',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'LO.Y' : {'headline': 'LOW WATER ADVISORY',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'LS.A' : {'headline': 'LAKESHORE FLOOD WATCH',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'LS.S' : {'headline': '',  # No headline for this VTEC
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'LS.W' : {'headline': 'LAKESHORE FLOOD WARNING',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'LS.Y' : {'headline': 'LAKESHORE FLOOD ADVISORY',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'LW.Y' : {'headline': 'LAKE WIND ADVISORY',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'MA.S' : {'headline': '',  # No headline for this VTEC
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'MA.W' : {'headline': 'SPECIAL MARINE WARNING',
              'overrideLock':'True',
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': False,
              'expirationTime': (-10, 10)
              },
    'MF.Y' : {'headline': 'DENSE FOG ADVISORY',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              }, # Marine Fog
    'MH.Y' : {'headline': 'ASHFALL ADVISORY',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              }, # Marine Ashfall
    'MS.Y' : {'headline': 'DENSE SMOKE ADVISORY',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              }, # Marine Smoke
    'RB.Y' : {'headline': 'SMALL CRAFT ADVISORY FOR ROUGH BAR',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'SC.Y' : {'headline': 'SMALL CRAFT ADVISORY',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'SE.A' : {'headline': 'HAZARDOUS SEAS WATCH',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'SE.W' : {'headline': 'HAZARDOUS SEAS WARNING',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'SI.Y' : {'headline': 'SMALL CRAFT ADVISORY FOR WINDS',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'SM.Y' : {'headline': 'DENSE SMOKE ADVISORY',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'SR.A' : {'headline': 'STORM WATCH',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'SR.W' : {'headline': 'STORM WARNING',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'SU.W' : {'headline': 'HIGH SURF WARNING',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'SU.Y' : {'headline': 'HIGH SURF ADVISORY',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },             
    'SV.A' : {'headline': 'SEVERE THUNDERSTORM WATCH',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'SV.W' : {'headline': 'SEVERE THUNDERSTORM WARNING',
              'overrideLock':'True',
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': False,
              'expirationTime': (-10, 10)
              },
    'SW.Y' : {'headline': 'SMALL CRAFT ADVISORY FOR HAZARDOUS SEAS',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'TI.A' : {'headline': 'TROPICAL STORM WIND WATCH',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'TI.W' : {'headline': 'TROPICAL STORM WIND WARNING',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'TO.A' : {'headline': 'TORNADO WATCH',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'TO.W' : {'headline': 'TORNADO WARNING',
              'subType':'' ,
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': False,
              'expirationTime': (-10, 10)
              },
    'TR.A' : {'headline': 'TROPICAL STORM WATCH',
              'subType':'' ,
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'TR.W' : {'headline': 'TROPICAL STORM WARNING',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'TS.A' : {'headline': 'TSUNAMI WATCH',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'TS.W' : {'headline': 'TSUNAMI WARNING',
              'overrideLock':'True',
              'combinableSegments': False,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'TY.A' : {'headline': 'TYPHOON WATCH',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'TY.W' : {'headline': 'TYPHOON WARNING',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'UP.A' : {'headline': 'HEAVY FREEZING SPRAY WATCH',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'UP.W' : {'headline': 'HEAVY FREEZING SPRAY WARNING',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'UP.Y' : {'headline': 'FREEZING SPRAY ADVISORY',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'WC.A' : {'headline': 'WIND CHILL WATCH',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'WC.W' : {'headline': 'WIND CHILL WARNING',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'WC.Y' : {'headline': 'WIND CHILL ADVISORY',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'WI.Y' : {'headline': 'WIND ADVISORY',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
             },
    'WS.A' : {'headline': 'WINTER STORM WATCH',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'WS.W' : {'headline': 'WINTER STORM WARNING',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'WW.Y' : {'headline': 'WINTER WEATHER ADVISORY',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'ZF.Y' : {'headline': 'FREEZING FOG ADVISORY',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
              },
    'ZR.Y' : {'headline': 'FREEZING RAIN ADVISORY',
              'overrideLock':'True',
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30)
             },
    }
