InputTestCaseData = { \
"caseDesc" : "Multiple frames generated by Hazard Services",
"sessionAttributes" :
{
    "staticSettings": {
        "defaultDuration": 1800000, 
        "defaultSiteID": "OAX"
    }, 
    "framesInfo": {
        "frameTimeList": [
            1297127700000, 
            1297128600000, 
            1297129500000, 
            1297130400000, 
            1297131300000, 
            1297132200000, 
            1297133100000, 
            1297134000000, 
            1297134900000, 
            1297135800000, 
            1297136700000, 
            1297137600000
        ], 
        "frameIndex": 11, 
        "currentFrame": "2011-02-08 04:00:00.0", 
        "frameCount": 12
    }, 
    "currentTime": 1297137600000
},
"spatialInputMap" :
{
    "spatialInfo": {
        "points": [
            [
                [
                    42.031920720344736, 
                    -95.35066746947292
                ], 
                1297137600.0
            ]
        ]
    }
}
}

TestCaseResults = \
{
    "pivots": [
        11
    ], 
    "forJavaObj": {
        "currentTime": 1297137600000, 
        "track": [
            [
                -96.21400716135585, 
                41.380872348945644
            ], 
            [
                -96.13624100449829, 
                41.440324001814005
            ], 
            [
                -96.05833229837219, 
                41.49972319051523
            ], 
            [
                -95.98028060943236, 
                41.5590697088945
            ], 
            [
                -95.90208550345284, 
                41.61836334999656
            ], 
            [
                -95.82374654553327, 
                41.67760390606294
            ], 
            [
                -95.74526330010495, 
                41.736791168529216
            ], 
            [
                -95.6666353309375, 
                41.7959249280223
            ], 
            [
                -95.58786220114514, 
                41.85500497435773
            ], 
            [
                -95.50894347319354, 
                41.91403109653686
            ], 
            [
                -95.42987870890653, 
                41.97300308274421
            ], 
            [
                -95.35066746947292, 
                42.031920720344736
            ], 
            [
                -95.27130931545365, 
                42.09078379588106
            ], 
            [
                -95.19180380678881, 
                42.14959209507082
            ]
        ], 
        "hazardPolygon": [
            [
                -95.19140441199104, 
                42.30859582799772
            ], 
            [
                -94.97733972728177, 
                42.14909672534867
            ], 
            [
                -95.35066736417097, 
                41.90471749928792
            ], 
            [
                -95.52192199250955, 
                42.03179351672527
            ]
        ], 
        "phenomena": "FF", 
        "subType": "Convective", 
        "SiteID": "OAX", 
        "startTime": 1297137600000, 
        "significance": "W", 
        "endTime": 1297139400000
    }, 
    "trackPoints": [
        {
            "pointType": "tracking", 
            "pointID": 1297127700000, 
            "shapeType": "point", 
            "point": [
                -96.21400716135585, 
                41.380872348945644
            ]
        }, 
        {
            "pointType": "tracking", 
            "pointID": 1297128600000, 
            "shapeType": "point", 
            "point": [
                -96.13624100449829, 
                41.440324001814005
            ]
        }, 
        {
            "pointType": "tracking", 
            "pointID": 1297129500000, 
            "shapeType": "point", 
            "point": [
                -96.05833229837219, 
                41.49972319051523
            ]
        }, 
        {
            "pointType": "tracking", 
            "pointID": 1297130400000, 
            "shapeType": "point", 
            "point": [
                -95.98028060943236, 
                41.5590697088945
            ]
        }, 
        {
            "pointType": "tracking", 
            "pointID": 1297131300000, 
            "shapeType": "point", 
            "point": [
                -95.90208550345284, 
                41.61836334999656
            ]
        }, 
        {
            "pointType": "tracking", 
            "pointID": 1297132200000, 
            "shapeType": "point", 
            "point": [
                -95.82374654553327, 
                41.67760390606294
            ]
        }, 
        {
            "pointType": "tracking", 
            "pointID": 1297133100000, 
            "shapeType": "point", 
            "point": [
                -95.74526330010495, 
                41.736791168529216
            ]
        }, 
        {
            "pointType": "tracking", 
            "pointID": 1297134000000, 
            "shapeType": "point", 
            "point": [
                -95.6666353309375, 
                41.7959249280223
            ]
        }, 
        {
            "pointType": "tracking", 
            "pointID": 1297134900000, 
            "shapeType": "point", 
            "point": [
                -95.58786220114514, 
                41.85500497435773
            ]
        }, 
        {
            "pointType": "tracking", 
            "pointID": 1297135800000, 
            "shapeType": "point", 
            "point": [
                -95.50894347319354, 
                41.91403109653686
            ]
        }, 
        {
            "pointType": "tracking", 
            "pointID": 1297136700000, 
            "shapeType": "point", 
            "point": [
                -95.42987870890653, 
                41.97300308274421
            ]
        }, 
        {
            "pointType": "tracking", 
            "pointID": 1297137600000, 
            "shapeType": "point", 
            "point": [
                -95.35066746947292, 
                42.031920720344736
            ]
        }, 
        {
            "pointType": "tracking", 
            "pointID": 1297138500000, 
            "shapeType": "point", 
            "point": [
                -95.27130931545365, 
                42.09078379588106
            ]
        }, 
        {
            "pointType": "tracking", 
            "pointID": 1297139400000, 
            "shapeType": "point", 
            "point": [
                -95.19180380678881, 
                42.14959209507082
            ]
        }
    ], 
    "pivotTimes": [
        1297137600000
    ], 
    "stormMotion": {
        "bearing": 225, 
        "speed": 20
    }, 
    "creationTime": 1297137600000, 
    "modifyCallbackToolName": "ModifyStormTrackTool", 
    "state": "pending", 
    "startTime": 1297137600000, 
    "endTime": 1297139400000, 
    "type": "FF.W"
}
