InputTestCaseData = { \
"caseDesc" : "Multiple frames generated by Hazard Services",
"sessionAttributes" :
{
    "framesInfo": {
        "frameTimeList": [
            1297127700000, 
            1297128600000, 
            1297129500000, 
            1297130400000, 
            1297131300000, 
            1297132200000, 
            1297133100000, 
            1297134000000, 
            1297134900000, 
            1297135800000, 
            1297136700000, 
            1297137600000
        ], 
        "frameIndex": 11, 
        "currentFrame": "2011-02-08 04:00:00.0", 
        "frameCount": 12
    }, 
    "currentTime": 1297137600000,
    "siteID" : "OAX"
},
"spatialInputMap" :
{
    "spatialInfo": {
        "points": [
            [
                [
                    42.031920720344736, 
                    -95.35066746947292
                ], 
                1297137600.0
            ]
        ]
    }
}
}

TestCaseResults = \
{
    "creationTime": 1297137600000, 
    "endTime": 1297141200000, 
    "forJavaObj": {
        "SiteID": "OAX", 
        "currentTime": 1297137600000, 
        "endTime": 1297141200000, 
        "hazardPolygon": [
            [
                -95.1913, 
                42.3403
            ], 
            [
                -94.9344, 
                42.1489
            ], 
            [
                -95.3506, 
                41.9047
            ], 
            [
                -95.5219, 
                42.0317
            ]
        ], 
        "phenomena": "FF", 
        "significance": "W", 
        "startTime": 1297137600000, 
        "subType": "Convective", 
        "track": [
            [
                -95.7845, 
                41.7072
            ], 
            [
                -95.7452, 
                41.7367
            ], 
            [
                -95.7059, 
                41.7663
            ], 
            [
                -95.6666, 
                41.7959
            ], 
            [
                -95.6272, 
                41.8254
            ], 
            [
                -95.5878, 
                41.855
            ], 
            [
                -95.5484, 
                41.8845
            ], 
            [
                -95.5089, 
                41.914
            ], 
            [
                -95.4694, 
                41.9435
            ], 
            [
                -95.4298, 
                41.973
            ], 
            [
                -95.3902, 
                42.0024
            ], 
            [
                -95.3506, 
                42.0319
            ], 
            [
                -95.311, 
                42.0613
            ], 
            [
                -95.2713, 
                42.0907
            ], 
            [
                -95.2315, 
                42.1201
            ], 
            [
                -95.1918, 
                42.1495
            ]
        ]
    }, 
    "modifyCallbackToolName": "ModifyStormTrackTool", 
    "pivotTimes": [
        1297137600000
    ], 
    "pivots": [
        11
    ], 
    "startTime": 1297137600000, 
    "state": "pending", 
    "stormMotion": {
        "bearing": 225, 
        "speed": 10
    }, 
    "trackPoints": [
        {
            "point": [
                -95.7845, 
                41.7072
            ], 
            "pointID": 1297127700000, 
            "pointType": "tracking", 
            "shapeType": "point"
        }, 
        {
            "point": [
                -95.7452, 
                41.7367
            ], 
            "pointID": 1297128600000, 
            "pointType": "tracking", 
            "shapeType": "point"
        }, 
        {
            "point": [
                -95.7059, 
                41.7663
            ], 
            "pointID": 1297129500000, 
            "pointType": "tracking", 
            "shapeType": "point"
        }, 
        {
            "point": [
                -95.6666, 
                41.7959
            ], 
            "pointID": 1297130400000, 
            "pointType": "tracking", 
            "shapeType": "point"
        }, 
        {
            "point": [
                -95.6272, 
                41.8254
            ], 
            "pointID": 1297131300000, 
            "pointType": "tracking", 
            "shapeType": "point"
        }, 
        {
            "point": [
                -95.5878, 
                41.855
            ], 
            "pointID": 1297132200000, 
            "pointType": "tracking", 
            "shapeType": "point"
        }, 
        {
            "point": [
                -95.5484, 
                41.8845
            ], 
            "pointID": 1297133100000, 
            "pointType": "tracking", 
            "shapeType": "point"
        }, 
        {
            "point": [
                -95.5089, 
                41.914
            ], 
            "pointID": 1297134000000, 
            "pointType": "tracking", 
            "shapeType": "point"
        }, 
        {
            "point": [
                -95.4694, 
                41.9435
            ], 
            "pointID": 1297134900000, 
            "pointType": "tracking", 
            "shapeType": "point"
        }, 
        {
            "point": [
                -95.4298, 
                41.973
            ], 
            "pointID": 1297135800000, 
            "pointType": "tracking", 
            "shapeType": "point"
        }, 
        {
            "point": [
                -95.3902, 
                42.0024
            ], 
            "pointID": 1297136700000, 
            "pointType": "tracking", 
            "shapeType": "point"
        }, 
        {
            "point": [
                -95.3506, 
                42.0319
            ], 
            "pointID": 1297137600000, 
            "pointType": "tracking", 
            "shapeType": "point"
        }, 
        {
            "point": [
                -95.311, 
                42.0613
            ], 
            "pointID": 1297138500000, 
            "pointType": "tracking", 
            "shapeType": "point"
        }, 
        {
            "point": [
                -95.2713, 
                42.0907
            ], 
            "pointID": 1297139400000, 
            "pointType": "tracking", 
            "shapeType": "point"
        }, 
        {
            "point": [
                -95.2315, 
                42.1201
            ], 
            "pointID": 1297140300000, 
            "pointType": "tracking", 
            "shapeType": "point"
        }, 
        {
            "point": [
                -95.1918, 
                42.1495
            ], 
            "pointID": 1297141200000, 
            "pointType": "tracking", 
            "shapeType": "point"
        }
    ], 
    "type": "FF.W"
}
