#!/bin/bash

##############################################################################
# Process Received Configuration
# This is run at the backup site to import the backed up site's Hazard Services
# site configuration into the localization store.
#
# SOFTWARE HISTORY
# Date         Ticket#    Engineer    Description
# ------------ ---------- ----------- --------------------------
# Sep 08, 2015 3473       Chris.Cody  Initial version
##############################################################################
if [ ${#AWIPS_HOME} = 0 ]
then
    AWIPS_HOME=/awips2
fi

export AWIPS_EDEX_SCRIPT_HOME=${AWIPS_HOME}/edex/scripts/HazardServices/ServiceBackup/scripts
export AWIPS_EDEX_CONFIG_HOME=${AWIPS_HOME}/edex/scripts/HazardServices/ServiceBackup/configuration

. ${AWIPS_EDEX_CONFIG_HOME}/svcbu.env
source ${AWIPS_EDEX_SCRIPT_HOME}/serviceBackupUtil.sh

# $1 = Path to packaged configuration data from MHS
# $2 = site ID for the file
if [ ${#1} = 0 ]
then
    configureLogging "hs_process_configuration" "ERR"
    echo "Null/Empty Path to packaged configuration data from MHS for Process Configuration. Fail. Exit 1"
    exit 1
fi
IMPORT_PATH_AND_FILE=${1}

if [ ${#2} = 0 ]
then
    configureLogging "hs_process_configuration" "ERR"
    echo "Null/Empty Site Id for Process Configuration. Fail. Exit 1"
    exit 1
fi
SITE_ID=`echo ${2} | tr '[A-Z]' '[a-z]'`
CAPS_SITE_ID=`echo ${SITE_ID}|tr [a-z] [A-Z]`

# Create the log file
configureLogging "hs_process_configuration" ${SITE_ID}

# Check the status of the lock file to see if we are OK to proceed
lock_file=$(getLockFile "hs_process_configuration" ${SITE_ID})
lock_status=$(isOperationInProgress "hs_process_configuration" ${SITE_ID})
echo "lock_status ${lock_status}"
if [[ "${lock_status}" = "true" ]]
then
    echo "Cannot import/process configuration for ${CAPS_SITE_ID}.  Import/process configuration process already in progress!"
    markTaskFailed ${lock_file}
    exit 1
fi

USER=$(whoami)
if [ $USER = "root" ]
then
    echo "Running script as root"
elif [ $USER = "awips" ]
then
    echo "Running script as user awips" 
else
    echo "Script must be run as user root or awips"
    markTaskFailed ${lock_file}
    exit 1
fi

if [ ${#AW_SITE_IDENTIFIER} = 0 ]; then
    echo "Mandatory variable: AW_SITE_IDENTIFIER unset. Program exits."
    markTaskFailed ${lock_file}
    exit 1
fi

markTaskInProgress ${lock_file}

if [ ! -f "${IMPORT_PATH_AND_FILE}" ]
then
    tempImportPathAndFile="${IMPORT_PATH_AND_FILE}/${HS_SVC_BKUP_PREFIX}${SITE_ID}.tar"
    if [ -f "${tempImportPathAndFile}" ]
    then
        IMPORT_PATH_AND_FILE="${tempImportPathAndFile}"
    else
        echo "Invalid or inaccessible Backup File: ${IMPORT_PATH_AND_FILE}. Fail. Exit 1"
        markTaskFailed ${lock_file}
        exit 1
    fi
else
    echo "Importing Backup File: ${IMPORT_PATH_AND_FILE}"
fi
HS_SVC_BKUP_FILENAME=$(basename ${IMPORT_PATH_AND_FILE})

if [ ${CAPS_SITE_ID} = ${AW_SITE_IDENTIFIER} ]; then
    echo "Cannot import Backup Site Data for the Local Site Id ${AW_SITE_IDENTIFIER}"
    markTaskFailed ${lock_file}
    exit 1
fi

# Retrieve the Site File for the Site to Backup
OUTPUT_DIR=$(getTempDirectory "hs_process_configuration" ${CAPS_SITE_ID})
if [ ${#OUTPUT_DIR} = 0 ]
then
    echo "Cannot find or build OUTPUT_DIR ${OUTPUT_DIR}"
    markTaskFailed ${lock_file}
    exit 1
fi

rm -rf ${OUTPUT_DIR}/*
cd ${OUTPUT_DIR}/

echo "Copying Site Config file from: ${IMPORT_PATH_AND_FILE} to ${OUTPUT_DIR}/"
cp -f ${IMPORT_PATH_AND_FILE} ${OUTPUT_DIR}/ 

# Update owner and permissions from root to awips
chown awips:awips ${OUTPUT_DIR}/${HS_SVC_BKUP_FILENAME} 
chmod 777 ${OUTPUT_DIR}/${HS_SVC_BKUP_FILENAME}

echo "Extracting files... for site ${CAPS_SITE_ID}"
tar -xvf ${HS_SVC_BKUP_FILENAME}
gunzip -c ${HS_SVC_CFG_TAR_PREFIX}.${SITE_ID}.tar.gz | tar xf -
if [ $? -ne 0 ]; then
    echo "\nERROR: Could not explode ${HS_SVC_CFG_TAR_PREFIX}.${SITE_ID}.tar.gz..."
    markTaskFailed ${lock_file}
    exit 1
fi

echo "Checking format of received configuration data..."
if [ -d ${HS_SVC_CFG_TAR_PREFIX} ]; then
    echo "AWIPS II configuration received.  OK to proceed!"
else
    echo "Incorrectly formatted configuration received.  Cannot continue!"
    markTaskFailed ${lock_file}
    exit 1
fi

echo "Checking if localization directories exist for ${CAPS_SITE_ID}"
edex_configured_dest=${LOCALIZATION_PATH}/edex_static/configured/${CAPS_SITE_ID}/hazardServices
edex_site_dest=${LOCALIZATION_PATH}/edex_static/site/${CAPS_SITE_ID}/hazardServices
common_configured_dest=${LOCALIZATION_PATH}/common_static/configured/${CAPS_SITE_ID}/hazardServices
common_site_dest=${LOCALIZATION_PATH}/common_static/site/${CAPS_SITE_ID}/hazardServices
cave_site_dest=${LOCALIZATION_PATH}/cave_static/site/${CAPS_SITE_ID}/hazardServices
rsync_parms_dest=/awips2/HazardServices/ServiceBackup/data

if [ -d ${edex_configured_dest} ]; then
    echo "edex_static configured site directory exists for ${CAPS_SITE_ID}"
else
    echo "Creating edex_static configured directory for ${CAPS_SITE_ID}" 
    mkdir -p ${edex_configured_dest}
fi

if [ -d ${edex_site_dest} ]; then
    echo "edex_static configured site directory exists for ${CAPS_SITE_ID}"
else
    echo "Creating edex_static site directory for ${CAPS_SITE_ID}" 
    mkdir -p ${edex_site_dest}
fi

if [ -d ${common_configured_dest} ]; then
    echo "common_static configured directory exists for ${CAPS_SITE_ID}"
else
    echo "Creating common_static configured directory for ${CAPS_SITE_ID}"
    mkdir -p ${common_configured_dest}
fi


if [ -d ${common_site_dest} ]; then
    echo "common_static site directory exists for ${CAPS_SITE_ID}"
else
    echo "Creating common_static site directory for ${CAPS_SITE_ID}"
    mkdir -p ${common_site_dest}
fi

if [ -d ${cave_site_dest} ]; then
    echo "cave_static site directory exists for ${CAPS_SITE_ID}"
else
    echo "Creating cave_static site directory for ${CAPS_SITE_ID}"
    mkdir -p ${cave_site_dest}
fi

if [ -d ${rsync_parms_dest} ]; then
    echo "rsync_parms_dest directory exists for ${CAPS_SITE_ID}"
else
    echo "Creating rsync_parms_dest directory for ${CAPS_SITE_ID}"
    mkdir -p ${rsync_parms_dest}
fi
echo "${CAPS_SITE_ID}'s localization directories have been verified"

echo "Copying ${OUTPUT_DIR}/${HS_SVC_CFG_TAR_PREFIX}/${CAPS_SITE_ID} files into localization directories under ${edex_configured_dest}"
cp -r ${OUTPUT_DIR}/${HS_SVC_CFG_TAR_PREFIX}/edex_static/configured/${CAPS_SITE_ID}/hazardServices ${edex_configured_dest}
cp -r ${OUTPUT_DIR}/${HS_SVC_CFG_TAR_PREFIX}/edex_static/site/${CAPS_SITE_ID}/hazardServices ${edex_site_dest}
cp -r ${OUTPUT_DIR}/${HS_SVC_CFG_TAR_PREFIX}/common_static/configured/${CAPS_SITE_ID}/hazardServices ${common_configured_dest}
cp -r ${OUTPUT_DIR}/${HS_SVC_CFG_TAR_PREFIX}/common_static/site/${CAPS_SITE_ID}/hazardServices  ${common_site_dest}
cp -r ${OUTPUT_DIR}/${HS_SVC_CFG_TAR_PREFIX}/cave_static/site/${CAPS_SITE_ID}/hazardServices ${cave_site_dest}
cp -a ${OUTPUT_DIR}/${HS_SVC_CFG_TAR_PREFIX}/site/rsync_parms.${SITE_ID} ${rsync_parms_dest}
echo "Files successfully copied!"


echo "Changing ownership of received configuration"
if [ $USER = "root" ]
then
    chown -R awips:fxalpha ${LOCALIZATION_PATH}/edex_static/configured/${CAPS_SITE_ID}/hazardServices
    chown -R awips:fxalpha ${LOCALIZATION_PATH}/edex_static/site/${CAPS_SITE_ID}/hazardServices
    chown -R awips:fxalpha ${LOCALIZATION_PATH}/common_static/configured/${CAPS_SITE_ID}/hazardServices
    chown -R awips:fxalpha ${LOCALIZATION_PATH}/common_static/site/${CAPS_SITE_ID}/hazardServices
    chown -R awips:fxalpha ${LOCALIZATION_PATH}/cave_static/site/${CAPS_SITE_ID}/hazardServices
elif [ $USER = "awips" ]
then
    echo "Files already owned by awips"
fi

# Cleanup
echo "Clean up work area ${OUTPUT_DIR}/*"
rm -rf ${OUTPUT_DIR}/* "
echo "Configuration Import Complete!"
markTaskSuccess ${lock_file}
exit 0


