# Note:   Booleans should not be prefixed with "is", i.e. isAllowAnyStartTime.  
#         Otherwise the deserialization will fail.
#
#         expirationTime is a tuple (beforeMinutes, afterMinutes).  
#                        This is set according to VTEC policy, so cannot be changed.
#                        If a hazard event is issued within the (beforeMinutes, afterMinutes)
#                        window around the hazard end time, then a VTEC EXP will be 
#                        automatically generated.  
#         hazardConflictList is a list of hazard types which conflict with the
#                            given hazard type.
#         ugcType represents the area type that a hazard geometry will
#                         be translated into when the hazard is issued. For example,
#                         A WS.W polygon will be translated into a collection of
#                         zones in the associated WSW when issued. 
#                         An FA.A will be translated into a 
#                         collection of counties in the associated FFA when issued.
#                         Some possible values include: county and zone. 
#                         These are the names of the corresponding tables
#                         in the maps db.
#         ugcLabel The label field to associate with the ugcType. 
#                          This corresponds to the label field associated with
#                          the maps db table which backs the hatch area. If
#                          hatch area is county, then label field does not apply.
#    inclusionFractionTest True - perform inclusion test
#                          False - do not perform inclusion test
#                          If this attribute is omitted, then inclusion testing will not
#                          be performed.
#        inclusionFraction The minimum fraction a hazard polygon must cover a UGC
#                          area before the UGC can be included in the UGC list.
#        inclusionAreaTest True - perform inclusion test
#                          False - do not perform inclusion test
#                          If this attribute is omitted, then inclusion area testing will not
#                          be performed.
#      inclusionAreaInSqKM The minimum area a hazard polygon must cover a UGC
#                          area before the UGC can be included in the UGC list.
#
#                          Note that if both inclusionFractionTest and inclusionAreaTest then 
#                          both tests must pass for inclusion.
#
#         hazardClipArea   The area, usually hsa or cwa, to restrict hazard geometries to.
#         hazardPointLimit The maximum number of vertices allowed for the hazard type. Excluding
#                          this field means that there is no point limit.
#         durationChoiceList Optional parameter. If not specified, the hazard type will use
#                           an absolute time selector for hazard event end time. If it is
#                           specified, it must be a list of one or more possible durations, 
#                           each of the form "num days", "num hours", "num minutes", or any
#                           combination of the three as long as it is ordered from largest
#                           to smallest unit, i.e. "2 days, 4 hours" is fine, but "4 hours,
#                           2 days" is not. The num must be a positive integer in each case.
#                           The "day" unit may be represented by "d", "day", or "days"; the
#                           "hour" unit by "h", "hr", "hrs", "hour", or "hours"; and the
#                           "minute" unit by "m", "mn", "min", "mins", "minute", or "minutes".
#                           Some examples of valid entries are "5 min", "20 minutes", "45m",
#                           "1 hr", "1h 30m" "1 hour, 45 minutes", "4 hrs", "1 day", "1d 12h",
#                           "2 days", "2 days, 240 minutes", and "3d 5h 20m".
#         defaultDuration   represents the default time duration for this hazard upon
#                           creation.  In milliseconds. (3600000 ms/hour, 60000 ms/minute)
#         durationIncrement represents the increment when setting the duration directly. 
#                           In minutes.
#         allowUntilFurtherNotice if True, the endTime of the hazard and/or the fallBelow
#                           time of the hazard can be set to "Until Further Notice".
#                           If entry is absent, then allowUntilFurtherNotice is False.
#                           Currently by policy only hazards in the FLW_FLS products use
#                           "Until Further Notice"
#         hatchingStyle     Either "NONE", "INTERSECTED_AREAS", or "WARNGEN". The latter
#                           is characterized by the following:
#                           *  When you add/remove UGCs the hatching changes but the polygon 
#                              remains unchanged until you preview.
#                           *  You will see W and Y symbols marking the area under threat.
#                           Defaults to INTERSECTED_AREAS.
#         hazardTypeFirstRecommender  Set the name of the recommender you want launched if the 
#                                     forecaster opts for the Hazard Type First workflow 
#         modifyRecommenders Optional parameter. If specified, it provides a mapping of
#                            the names of recommenders to lists of hazard attributes that
#                            should trigger those recommenders to be run when any of the
#                            given attributes are changed. The actual value must be a
#                            dictionary, with each key being the name of a recommender, and
#                            the associated value being a list holding the names of attributes
#                            that when changed trigger the running of that recommender. Valid
#                            attributes are "timeRange", "geometry", "visualFeature", and
#                            "status".  (Note that any hazard event attributes that may be
#                            specific to a hazard type, e.g. "cta", may be made triggers as
#                            well within a hazard type's metadata generation script.) 
#         startTimeIsCurrentTime: Affects unissued and issued; if true, start time is never
#                                 editable by the user, and must be the current CAVE clock
#                                 time.  Default is False.
#         allowAnyStartTime:
#                          Affects unissued and issued events; if true, start time can be
#                          before, the same as, or later than the current time. If true and
#                          "startTimeIsCurrentTime" is false, this overrules the latter.
#                          Default is False.
#         allowTimeExpand: Affects issued events only; if true, an event can have its end time
#                          pulled right (made later than it was). Default is True.
#         allowTimeShrink: Affects issued events only; if true, an event can have its end time
#                          pulled left (made sooner than what it was). Default is True.
#         requirePointId:  Indicates whether or not must have a "pointID" attribute value.
#                          Default is False.
#         pointBased:      Indicates whether or not the hazard type is point-based. Default is
#                          False.
#         allowTimeChange: Ignored by the GUI; used in VTEC processing
#         allowAreaChange: Ignored by the GUI; used in VTEC processing
#         combinableSegments:  
#                          If False, hazard events are treated as separate ETN's i.e. they
#                          are not combined into a single segment.  A hazard event can have multiple polygons if needed.
#                          If True, Hazard Events can be combined into one segment.   
#         includeAll:   If True, all events in the allowedHazard group need to be included when generating 
#                       products e.g. ALL FF.A hazard events need to be included when creating an FFA product.
#         allowOverlappingPolygons: If True, hazard events can contain multiple overlapping polygons.  
#                       If False or not specified, overlapping polygons added to the event will be unioned with the existing polygons.

HOURS = 3600000
MINUTES = 60000
OVERRIDE_LOCK =  ['headline', 'combinableSegments', 'includeAll', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True]
HazardTypes = {
    'AF.Y' : {'headline': 'ASHFALL ADVISORY',
              '_override_lock_': OVERRIDE_LOCK, 
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['AF.W'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,  # 8 hours
              'durationIncrement': 60,
              },
    'AF.W' : {'headline': 'ASHFALL WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['AF.Y'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,  # 8 hours
              'durationIncrement': 60,
              },
    'AQ.Y' : {'headline': 'AIR QUALITY ALERT',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['AS.O', 'AS.Y'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'AS.O' : {'headline': 'AIR STAGNATION OUTLOOK',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['AQ.Y', 'AS.Y'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'AS.Y' : {'headline': 'AIR STAGNATION ADVISORY',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['AQ.Y', 'AS.O'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'BH.S' : {'headline': 'BEACH HAZARD STATEMENT',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['HU.A', 'TR.A', 'TY.A', 'CF.Y', 'CF.W', 'CF.A', 'SS.A', 'SS.W'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'BW.Y' : {'headline': 'BRISK WIND ADVISORY',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['GL.W', 'SR.W', 'HF.W', 'TR.A', 'TR.W', 'HU.A', 'HU.W', 'SC.Y', 'SW.Y', 'SE.W', 'RB.Y', 'SI.Y'],
              'ugcType': 'marinezones',
              'ugcLabel': 'name',
              'hazardClipArea' : 'marinezones',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'BZ.A' : {'headline' : 'BLIZZARD WATCH',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['LE.A', 'WS.A', 'BZ.W', 'IS.W', 'LE.W', 'WS.W', 'WW.Y', 'LE.Y', 'ZR.Y'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'BZ.W' : {'headline' : 'BLIZZARD WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['BZ.A', 'LE.A', 'WS.A', 'IS.W', 'LE.W', 'WS.W', 'WW.Y', 'LE.Y', 'ZR.Y'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'CF.A' : {'headline': 'COASTAL FLOOD WATCH',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['CF.W', 'CF.Y', 'HU.A', 'HU.W', 'SS.A', 'SS.W', 'TR.A', 'TY.A', 'TR.W'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea': 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'CF.W' : {'headline': 'COASTAL FLOOD WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True, 
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['CF.A', 'CF.Y', 'HU.W', 'SS.A', 'SS.W', 'TR.W', 'TY.W'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'CF.Y' : {'headline': 'COASTAL FLOOD ADVISORY',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True, 
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['CF.W', 'CF.A', 'HU.W', 'SS.A', 'SS.W', 'TR.W', 'TY.W'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea': 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'CF.S' : {'headline': '',  # No headline for this VTEC
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['HU.A', 'TR.A', 'TY.A', 'CF.Y', 'CF.W', 'CF.A', 'SS.A', 'SS.W'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'DS.W' : {'headline': 'DUST STORM WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['DU.Y'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'DU.Y' : {'headline': 'BLOWING DUST ADVISORY',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['DS.W'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
             'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'EC.A' : {'headline': 'EXTREME COLD WATCH',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['WC.A', 'EC.W', 'WC.W'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'EC.W' : {'headline': 'EXTREME COLD WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['EC.A', 'WC.A', 'WC.W', 'WC.Y'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'EH.A' : {'headline': 'EXCESSIVE HEAT WATCH',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['EH.W', 'HT.Y'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'EH.W' : {'headline': 'EXCESSIVE HEAT WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['EH.A', 'HT.Y'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'EW.W' : {'headline': 'EXTREME WIND WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': False,
              'expirationTime': (-10, 10),
              'hazardConflictList': ['TO.W', 'SV.W'],
              'ugcType': 'county',
              'ugcLabel': '',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 30 * MINUTES,
              'durationIncrement': 1,
              'startTimeIsCurrentTime': True,
              'allowTimeExpand': False,
              'allowTimeShrink': False,
              },
    'FA.A' : {'headline': 'AREAL FLOOD WATCH',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['FF.A'],
              'hatchingStyle': "INTERSECTED_AREAS",
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest': True,
              'inclusionFraction': 0.1,
              'inclusionAreaTest' : True,
              'inclusionAreaInSqKm' : 1.0,
              'replacedBy': ['FA.W', 'FA.Y'],
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'FA.W' : {'headline': 'AREAL FLOOD WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-10, 10),
              'hazardConflictList': [],
              'hatchingStyle': "WARNGEN",
              'ugcType': 'county',
              'ugcLabel': '',
              'hazardClipArea' : 'cwa',
              'replacedBy': ['FA.Y'],
              'hazardPointLimit': 20,
              'durationChoiceList': [ "60 min", "90 min", "120 min", "3 hrs", "6 hrs", "9 hrs", "12 hrs", "24 hrs", "1 day 12 hrs", "2 days", "2 days 12 hrs", "3 days", "4 days", "5 days", "6 days", "7 days" ],
              'defaultDuration': 3 * HOURS,
              'durationIncrement': 15,
              'inclusionFractionTest': True,
              'inclusionFraction': 0.1,
              'inclusionAreaTest' : True,
              'inclusionAreaInSqKm' : 1.0,
              'startTimeIsCurrentTime': True,
              'allowTimeExpand': True,
              'allowTimeShrink': False,
              },
    'FA.Y' : {'headline': 'AREAL FLOOD ADVISORY',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-10, 10),
              'hatchingStyle': "WARNGEN",
              'ugcType': 'county',
              'ugcLabel': '',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest': True,
              'inclusionFraction': 0.1,
              'inclusionAreaTest' : True,
              'inclusionAreaInSqKm' : 1.0,
              'hazardConflictList': [],
              'hazardPointLimit': 20,
              'replacedBy': ['FA.W'],
              'durationChoiceList': [ "60 min", "120 min", "3 hrs", "3 hrs 30 min", "4 hrs", "4 hrs 30 min", "5 hrs", "5 hrs 30 min", "6 hrs", "7 hrs", "8 hrs", "9 hrs", "10 hrs", "11 hrs", "12 hrs", "24 hrs", "1 day 12 hrs", "2 days", "2 days 12 hrs" ],
              'defaultDuration': 3 * HOURS,
              'durationIncrement': 15,
              'inclusionFractionTest': True,
              'inclusionFraction': 0.1,
              'inclusionAreaTest' : True,
              'inclusionAreaInSqKm' : 1.0,
              'startTimeIsCurrentTime': True,
              'allowTimeExpand': True,
              'allowTimeShrink': False,
              },
    'FF.A' : {'headline': 'FLASH FLOOD WATCH',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True, 
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['FA.A'],
              'hatchingStyle': "INTERSECTED_AREAS",
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest': True,
              'inclusionFraction': 0.1,
              'inclusionAreaTest' : True,
              'inclusionAreaInSqKm' : 1.0,
              'replacedBy': ['FF.W.Convective', 'FF.W.NonConvective'],
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              'hazardTypeFirstRecommender':'StormTrackTool',
              },
    'FF.W.BurnScar' : {
              'headline': 'FLASH FLOOD WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-10, 10),
              'hazardConflictList': [],
              'hatchingStyle': "WARNGEN",
              'ugcType': 'county',
              'ugcLabel': '',
              'hazardClipArea' : 'cwa',
              'hazardPointLimit' : 20,
              'durationChoiceList': [ "30 min", "45 min", "60 min", "90 min", "120 min", "3 hrs", "4 hrs", "6 hrs", "8 hrs"],
              'defaultDuration': 45 * MINUTES,
              'durationIncrement': 15,
              'inclusionFractionTest': False,
              'inclusionFraction': 0.1,
              'inclusionAreaTest' : True,
              'inclusionAreaInSqKm' : 1.0,
              'hazardTypeFirstRecommender':'StormTrackTool',
              'startTimeIsCurrentTime': True,
              'allowTimeExpand': True,
              'allowTimeShrink': False,
              },
    'FF.W.Convective' : {
              'headline': 'FLASH FLOOD WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-10, 10),
              'hazardConflictList': [],
              'hatchingStyle': "WARNGEN",
              'ugcType': 'county',
              'ugcLabel': '',
              'hazardClipArea' : 'cwa',
              'hazardPointLimit': 20,
              'durationChoiceList': [ "60 min", "90 min", "120 min", "2 hrs 30 min", "3 hrs", "3 hrs 30 min", "4 hrs", "4 hrs 30 min", "5 hrs", "5 hrs 30 min", "6 hrs", "6 hrs 30 min", "7 hrs", "7 hrs 30 min", "8 hrs" ],
              'defaultDuration': 1 * HOURS,
              'durationIncrement': 15,
              'hazardTypeFirstRecommender':'StormTrackTool',
              'inclusionFractionTest': True,
              'inclusionFraction': 0.1,
              'inclusionAreaTest' : True,
              'inclusionAreaInSqKm' : 1.0,
              'startTimeIsCurrentTime': True,
              'allowTimeExpand': True,
              'allowTimeShrink': False,
              'modifyRecommenders': {
                                     'StormTrackTool': [ "geometry", "status", "timeRange", "visualFeature" ]
                                     },
              },
    'FF.W.NonConvective' : {
              'headline': 'FLASH FLOOD WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-10, 10),
              'hazardConflictList': [],
              'hatchingStyle': "WARNGEN",
              'ugcType': 'county',
              'ugcLabel': '',
              'hazardClipArea' : 'cwa',
              'hazardPointLimit' : 20,
              'durationChoiceList': [ "60 min", "90 min", "120 min", "3 hrs", "6 hrs", "9 hrs", "12 hrs", "24 hrs", "1 day 12 hrs", "2 days", "2 days 12 hrs", "3 days", "4 days", "5 days", "6 days", "7 days" ],
              'defaultDuration': 3 * HOURS,
              'durationIncrement': 15,
              'inclusionFractionTest': True,
              'inclusionFraction': 0.1,
              'inclusionAreaTest' : True,
              'inclusionAreaInSqKm' : 1.0,
              'hazardTypeFirstRecommender':'StormTrackTool',
              'startTimeIsCurrentTime': True,
              'allowTimeExpand': True,
              'allowTimeShrink': False,
              },
    'FG.Y' : {'headline': 'DENSE FOG ADVISORY',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'FL.A' : {'headline': 'RIVER FLOOD WATCH',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'hatchingStyle': "INTERSECTED_AREAS",
              'pointBased': True,
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest': True,
              'inclusionFraction': 0.1,
              'inclusionAreaTest' : True,
              'inclusionAreaInSqKm' : 1.0,
              'replacedBy': ['FL.W', 'FL.Y'],
              'defaultDuration': 8 * HOURS,
              'allowUntilFurtherNotice': True,
              'durationIncrement': 60,
              'requirePointId': True
              },
    'FL.W' : {'headline': 'RIVER FLOOD WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'hatchingStyle': "INTERSECTED_AREAS",
              'pointBased': True,
              'ugcType': 'county',
              'ugcLabel': '',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest': True,
              'inclusionFraction': 0.1,
              'inclusionAreaTest' : True,
              'inclusionAreaInSqKm' : 1.0,
              'replacedBy': ['FL.Y'],
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              'allowUntilFurtherNotice': True,
              'requirePointId': True
              },
    'FL.Y' : {'headline': 'RIVER FLOOD ADVISORY',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'hatchingStyle': "INTERSECTED_AREAS",
              'pointBased': True,
              'ugcType': 'county',
              'ugcLabel': '',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest': True,
              'inclusionFraction': 0.1,
              'inclusionAreaTest' : True,
              'inclusionAreaInSqKm' : 1.0,
              'replacedBy': ['FL.W'],
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              'allowUntilFurtherNotice': True,
              'requirePointId': True
              },
    'FR.Y' : {'headline': 'FROST ADVISORY',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['FZ.A', 'FZ.W', 'HZ.W', 'HZ.A'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'FW.A' : {'headline': 'FIRE WEATHER WATCH',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['FW.W'],
              'ugcType': 'firewxzones',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'ugcLabel': 'name',
              'hazardClipArea' : 'firewxzones',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'FW.W' : {'headline': 'RED FLAG WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['FW.A'],
              'ugcType': 'firewxzones',
              'ugcLabel': 'name',
              'hazardClipArea' : 'firewxzones',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'FZ.A' : {'headline': 'FREEZE WATCH',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['FZ.W', 'FR.Y', 'HZ.W', 'HZ.A'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'FZ.W' : {'headline': 'FREEZE WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['FZ.A', 'FR.Y', 'HZ.W', 'HZ.A'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'GL.A' : {'headline': 'GALE WATCH',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['SR.W', 'HF.W', 'TR.A', 'TR.W', 'HU.A', 'HU.W', 'SE.W', 'GL.W', 'SR.A', 'HF.A', 'SE.A', 'TY.A', 'TY.W'],
              'ugcType': 'marinezones',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'marinezones',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'GL.W' : {'headline': 'GALE WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList':  ['SR.W', 'HF.W', 'BW.Y', 'TR.W', 'HU.W', 'SC.Y', 'SW.Y', 'SE.W', 'RB.Y', 'SI.Y', 'GL.A', 'SE.A', 'TY.W'],
              'ugcType': 'marinezones',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'marinezones',
              'defaultDuration': 8 * 360000,
              'durationIncrement': 60,
              },
    'HF.A' : {'headline': 'HURRICANE FORCE WIND WATCH',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['TR.A', 'TR.W', 'HU.A', 'HU.W', 'GL.A', 'SR.A', 'HF.W', 'SE.A', 'TY.A', 'TY.W'],
              'ugcType': 'marinezones',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'marinezones',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'HF.W' : {'headline': 'HURRICANE FORCE WIND WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList':['GL.W', 'SR.W', 'BW.Y', 'TR.A', 'TR.W', 'HU.A', 'HU.W', 'SC.Y', 'SW.Y', 'SE.W', 'RB.Y', 'SI.Y', 'GL.A', 'SR.A', 'HF.A', 'SE.A', 'TY.W', 'TY.A'],
              'ugcType': 'marinezones',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'marinezones',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'HT.Y' : {'headline': 'HEAT ADVISORY',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['EH.A', 'EH.W'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'HU.A' : {'headline': 'HURRICANE WATCH',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': False,
              'expirationTime': (-30, 30),
              'hazardConflictList':['TR.A', 'HU.W', 'GL.A', 'SR.A', 'HF.W', 'SE.A', 'CF.S', 'CF.A', 'HW.A' ],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'HU.W' : {'headline': 'HURRICANE WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': False,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['GL.W', 'SR.W', 'HF.W', 'BW.Y', 'TR.A', 'TR.W', 'HU.A', 'SC.Y', 'SW.Y', 'SE.W', 'RB.Y', 'SI.Y', 'GL.A', 'SR.A', 'HF.A', 'SE.A', 'CF.W', 'CF.A', 'CF.Y', 'CF.S', 'SU.W', 'SU.Y', 'HW.W', 'WI.Y', 'HW.A', 'LW.Y'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              'allowTimeExpand': False,
              'allowTimeShrink': False,
              },
    'HW.A' : {'headline': 'HIGH WIND WATCH',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['HW.W', 'LW.Y', 'WI.Y', 'TR.A', 'TR.W', 'HU.A', 'HU.W', 'TY.A', 'TY.W'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'HW.W' : {'headline': 'HIGH WIND WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['HW.A', 'LW.Y', 'WI.Y', 'TR.A', 'HU.A', 'TY.A', 'TR.W', 'HU.W', 'TY.W'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'HY.O' : {'headline': 'HYDROLOGIC OUTLOOK',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': False,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'ugcType': 'county',
              'ugcLabel': 'countyName',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'HY.S' : {'headline': 'FORECAST INFORMATION',  # No headline for this VTEC
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],  # ['FL.W', 'FL.Y', 'FL.A'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'replacedBy': ['FL.A', 'FL.Y', 'FL.W'],
              'pointBased': True,
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest': True,
              'inclusionFraction': 0.1,
              'inclusionAreaTest' : True,
              'inclusionAreaInSqKm' : 1.0,
              'allowUntilFurtherNotice': True,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              'requirePointId': True
              },
    'HZ.A' : {'headline': 'HARD FREEZE WATCH',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['FZ.W', 'FR.Y', 'FZ.A', 'HZ.W'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'HZ.W' : {'headline': 'HARD FREEZE WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['FZ.A', 'FR.Y', 'HZ.A', 'FZ.W'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'IS.W' : {'headline': 'ICE STORM WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['BZ.A', 'LE.A', 'WS.A', 'BZ.W', 'WS.W', 'LE.W', 'WW.Y', 'LE.Y', 'ZR.Y'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'LE.A' : {'headline': 'LAKE EFFECT SNOW WATCH',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['BZ.A', 'WS.A', 'BZ.W', 'IS.W', 'WS.W', 'LE.W', 'WW.Y', 'LE.Y', 'ZR.Y'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'LE.W' : {'headline': 'LAKE EFFECT SNOW WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['BZ.A', 'LE.A', 'WS.A', 'BZ.W', 'IS.W', 'WS.W', 'WW.Y', 'LE.Y', 'ZR.Y'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'LE.Y' : {'headline': 'LAKE EFFECT SNOW ADVISORY',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['BZ.A', 'LE.A', 'WS.A', 'BZ.W', 'IS.W', 'LE.W', 'WS.W', 'WW.Y', 'ZR.Y'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'LO.Y' : {'headline': 'LOW WATER ADVISORY',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'LS.A' : {'headline': 'LAKESHORE FLOOD WATCH',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['LS.W', 'LS.Y'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'LS.W' : {'headline': 'LAKESHORE FLOOD WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['LS.A', 'LS.Y'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'LS.Y' : {'headline': 'LAKESHORE FLOOD ADVISORY',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['LS.A', 'LS.W'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'LW.Y' : {'headline': 'LAKE WIND ADVISORY',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList':  ['HW.A', 'HW.W', 'WI.Y', 'TR.A', 'HU.A', 'TY.A', 'TR.W', 'HU.W', 'TY.W'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'MA.S' : {'headline': '',  # No headline for this VTEC
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'ugcType': '',
              'ugcLabel': '',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'MA.W' : {'headline': 'SPECIAL MARINE WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': False,
              'expirationTime': (-10, 10),
              'hazardConflictList': [],
              'ugcType': 'county',
              'ugcLabel': '',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'marinezones',
              'defaultDuration': 30 * MINUTES,
              'durationIncrement': 15,
              'startTimeIsCurrentTime': True,
              'allowTimeExpand': False,
              'allowTimeShrink': False,
              },
    'MF.Y' : {'headline': 'DENSE FOG ADVISORY',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'ugcType': 'marinezones',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'marinezones',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },  # Marine Fog
    'MH.Y' : {'headline': 'ASHFALL ADVISORY',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['MH.W'],
              'ugcType': 'marinezones',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'marinezones',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },  # Marine Ashfall
    'MS.Y' : {'headline': 'DENSE SMOKE ADVISORY',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'ugcType': 'marinezones',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'marinezones',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },  # Marine Smoke
    'RB.Y' : {'headline': 'SMALL CRAFT ADVISORY FOR ROUGH BAR',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList':  ['SR.W', 'HF.W', 'BW.Y', 'TR.W', 'HU.W', 'SE.W', 'GL.W', 'TY.W'],
              'ugcType': 'marinezones',
              'ugcLabel': 'name',
              'hazardClipArea' : 'marinezones',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'SC.Y' : {'headline': 'SMALL CRAFT ADVISORY',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList':  ['SR.W', 'HF.W', 'BW.Y', 'TR.W', 'HU.W', 'SE.W', 'GL.W', 'TY.W'],
              'ugcType': 'marinezones',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'marinezones',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'SE.A' : {'headline': 'HAZARDOUS SEAS WATCH',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['SE.W', 'GL.W', 'SR.W', 'HF.W', 'BW.Y', 'TR.W', 'HU.W', 'GL.A', 'SR.A', 'HF.A', 'TR.A', 'HU.A', 'TY.W', 'TY.A'],
              'ugcType': 'marinezones',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'marinezones',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'SE.W' : {'headline': 'HAZARDOUS SEAS WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['GL.W', 'SR.W', 'BW.Y', 'TR.W', 'HU.W', 'SC.Y', 'SW.Y', 'RB.Y', 'SI.Y', 'GL.A', 'HF.W', 'SE.A', 'TY.W'],
              'ugcType': 'marinezones',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'marinezones',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'SI.Y' : {'headline': 'SMALL CRAFT ADVISORY FOR WINDS',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['GL.W', 'SE.W', 'SR.W', 'HF.W', 'BW.Y', 'TR.W', 'HU.W', 'TY.W'],
              'ugcType': 'marinezones',
              'ugcLabel': 'name',
              'hazardClipArea' : 'marinezones',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'SM.Y' : {'headline': 'DENSE SMOKE ADVISORY',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'SR.A' : {'headline': 'STORM WATCH',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList':['SR.W', 'HF.W', 'BW.Y', 'TR.W', 'HU.W', 'GL.A', 'SR.A', 'HF.A', 'TR.A', 'HU.A', 'TY.W', 'TY.A'],
              'ugcType': 'marinezones',
              'ugcLabel': 'name',
              'hazardClipArea' : 'marinezones',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'SR.W' : {'headline': 'STORM WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['GL.W', 'HF.W', 'BW.Y', 'TR.W', 'HU.W', 'TY.W', 'SC.Y', 'SW.Y', 'SE.W', 'SE.A', 'RB.Y', 'SI.Y', 'GL.A', 'SR.A'],
              'ugcType': 'marinezones',
              'ugcLabel': 'name',
              'hazardClipArea' : 'marinezones',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'SU.W' : {'headline': 'HIGH SURF WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['SU.Y', 'HU.W', 'TR.W', 'TY.W'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'SU.Y' : {'headline': 'HIGH SURF ADVISORY',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['SU.W', 'HU.W', 'TR.W', 'TY.W'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'SV.A' : {'headline': 'SEVERE THUNDERSTORM WATCH',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['TO.A'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'SV.W' : {'headline': 'SEVERE THUNDERSTORM WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': False,
              'expirationTime': (-10, 10),
              'hazardConflictList': [],
              'ugcType': 'county',
              'ugcLabel': '',
              'hazardClipArea' : 'cwa',
              'defaultDuration': 30 * MINUTES,
              'durationIncrement': 15,
              'startTimeIsCurrentTime': True,
              'allowTimeExpand': False,
              'allowTimeShrink': False,
              },
    'SW.Y' : {'headline': 'SMALL CRAFT ADVISORY FOR HAZARDOUS SEAS',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['SE.W', 'GL.W', 'SR.W', 'HF.W', 'BW.Y', 'TR.W', 'HU.W', 'TY.W'],
              'ugcType': 'marinezones',
              'ugcLabel': 'name',
              'hazardClipArea' : 'marinezones',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'TO.A' : {'headline': 'TORNADO WATCH',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['SV.A'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'TO.W' : {'headline': 'TORNADO WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': False,
              'expirationTime': (-10, 10),
              'hazardConflictList': [],
              'ugcType': 'county',
              'ugcLabel': '',
              'hazardClipArea' : 'cwa',
              'defaultDuration': 30 * MINUTES,
              'durationIncrement': 15,
              'startTimeIsCurrentTime': True,
              'allowTimeExpand': False,
              'allowTimeShrink': False,
              },
    'TR.A' : {'headline': 'TROPICAL STORM WATCH',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': False,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['HU.A', 'HU.W', 'TY.A', 'TY.W', 'TR.W', 'HW.A', 'GL.A', 'SE.A', 'SR.A', 'SR.W', 'HF.W', 'CF.S', 'CF.A'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              'allowTimeExpand': False,
              'allowTimeShrink': False,
              },
    'TR.W' : {'headline': 'TROPICAL STORM WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': False,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['GL.W', 'SR.W', 'HF.W', 'BW.Y', 'TR.A', 'TY.W', 'HU.W', 'SC.Y', 'SW.Y', 'SE.W', 'RB.Y', 'SI.Y', 'GL.A', 'SR.A', 'HF.A', 'SE.A', 'CF.W', 'CF.A', 'CF.Y', 'CF.S', 'SU.W', 'SU.Y', 'HW.W', 'WI.Y', 'HW.A', 'LW.Y'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              'allowTimeExpand': False,
              'allowTimeShrink': False,
              },
    'TS.A' : {'headline': 'TSUNAMI WATCH',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['TS.W'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'TS.W' : {'headline': 'TSUNAMI WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['TS.A'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'TY.A' : {'headline': 'TYPHOON WATCH',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': False,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['TR.A', 'TY.W', 'GL.A', 'SR.A', 'HF.W', 'SE.A', 'CF.S', 'CF.A', 'HW.A' ],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              'allowTimeExpand': False,
              'allowTimeShrink': False,
              },
    'TY.W' : {'headline': 'TYPHOON WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': False,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['GL.W', 'SR.W', 'HF.W', 'BW.Y', 'TR.A', 'TR.W', 'TY.A', 'SC.Y', 'SW.Y', 'SE.W', 'RB.Y', 'SI.Y', 'GL.A', 'SR.A', 'HF.A', 'SE.A', 'CF.W', 'CF.A', 'CF.Y', 'CF.S', 'SU.W', 'SU.Y', 'HW.W', 'WI.Y', 'HW.A', 'LW.Y'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              'allowTimeExpand': False,
              'allowTimeShrink': False,
              },
    'UP.A' : {'headline': 'HEAVY FREEZING SPRAY WATCH',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['UP.W', 'UP.Y'],
              'ugcType': 'marinezones',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'marinezones',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'UP.W' : {'headline': 'HEAVY FREEZING SPRAY WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['UP.A', 'UP.Y'],
              'ugcType': 'marinezones',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'UP.Y' : {'headline': 'FREEZING SPRAY ADVISORY',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList':['UP.A', 'UP.W'],
              'ugcType': 'marinezones',
              'ugcLabel': 'name',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'hazardClipArea' : 'marinezones',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'WC.A' : {'headline': 'WIND CHILL WATCH',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['WC.Y', 'WC.W'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'WC.W' : {'headline': 'WIND CHILL WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['WC.A', 'WC.Y'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'WC.Y' : {'headline': 'WIND CHILL ADVISORY',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['WC.A', 'WC.W'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'WI.Y' : {'headline': 'WIND ADVISORY',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['HW.A', 'HW.W', 'LW.Y', 'TR.A', 'HU.A', 'TY.A', 'TR.W', 'HU.W', 'TY.W'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
             },
    'WS.A' : {'headline': 'WINTER STORM WATCH',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['BZ.A', 'LE.A', 'BZ.W', 'IS.W', 'WS.W', 'LE.W', 'WW.Y', 'LE.Y', 'ZR.Y'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'WS.W' : {'headline': 'WINTER STORM WARNING',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['BZ.A', 'LE.A', 'WS.A', 'BZ.W', 'IS.W', 'LE.W', 'WW.Y', 'LE.Y', 'ZR.Y'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'WW.Y' : {'headline': 'WINTER WEATHER ADVISORY',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['BZ.A', 'LE.A', 'WS.A', 'BZ.W', 'IS.W', 'WS.W', 'LE.W', 'LE.Y', 'ZR.Y'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'ZF.Y' : {'headline': 'FREEZING FOG ADVISORY',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['FG.Y'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              },
    'ZR.Y' : {'headline': 'FREEZING RAIN ADVISORY',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['BZ.A', 'LE.A', 'WS.A', 'BZ.W', 'IS.W', 'WS.W', 'LE.W', 'WW.Y', 'LE.Y'],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
             },
               
    ######################
    # Probabilistic
    
    ##########
    # National Center Prob Hazards
    
    # Storm Prediction Center
    'Prob_Convection' : {'headline': 'Categorical Convective Outlook',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': False,
              'allowTimeChange': False,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              #'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              'allowOverlappingPolygons': True,
              },

    'Prob_Convection.Thunderstorms' : {'headline': 'Thunderstorms TSTM',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': False,
              'allowTimeChange': False,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              #'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              'allowOverlappingPolygons': True,
              },
    'Prob_Convection.Marginal' : {'headline': 'Convection Marginal MRGL',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': False,
              'allowTimeChange': False,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              #'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              'allowOverlappingPolygons': True,
              },
    'Prob_Convection.Slight' : {'headline': 'Convection Slight SLGT',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': False,
              'allowTimeChange': False,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              #'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              'allowOverlappingPolygons': True,
              },
    'Prob_Convection.Enhanced' : {'headline': 'Convection Enhanced ENH',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': False,
              'allowTimeChange': False,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              #'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              'allowOverlappingPolygons': True,
              },
    'Prob_Convection.Moderate' : {'headline': 'Convection Moderate MDT',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': False,
              'allowTimeChange': False,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              #'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              'allowOverlappingPolygons': True,
              },
    'Prob_Convection.High' : {'headline': 'Convection High HIGH',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': False,
              'allowTimeChange': False,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              #'hazardClipArea' : 'cwa',
              'inclusionFractionTest' : True,
              'inclusionFraction': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60,
              'allowOverlappingPolygons': True,
              },
               
    # Weather Prediction Center          
    'Prob_Rainfall' : {'headline': 'Excessive Rainfall Outlook',
          '_override_lock_': OVERRIDE_LOCK,
          'combinableSegments': True,
          'includeAll': True,
          'allowAreaChange': False,
          'allowTimeChange': False,
          'expirationTime': (-30, 30),
          'hazardConflictList': [],
          'ugcType': 'zone',
          'ugcLabel': 'name',
          #'hazardClipArea' : 'cwa',
          'inclusionFractionTest' : True,
          'inclusionFraction': 0.1,
          'defaultDuration': 8 * HOURS,
          'durationIncrement': 60,
          'allowOverlappingPolygons': True,
          },

    'Prob_Rainfall.SeeText' : {'headline': 'See Text for Excessive Rainfall <5%',
          '_override_lock_': OVERRIDE_LOCK,
          'combinableSegments': True,
          'includeAll': True,
          'allowAreaChange': False,
          'allowTimeChange': False,
          'expirationTime': (-30, 30),
          'hazardConflictList': [],
          'ugcType': 'zone',
          'ugcLabel': 'name',
          #'hazardClipArea' : 'cwa',
          'inclusionFractionTest' : True,
          'inclusionFraction': 0.1,
          'defaultDuration': 8 * HOURS,
          'durationIncrement': 60,
          'allowOverlappingPolygons': True,
          },
    'Prob_Rainfall.Slight' : {'headline': 'Slight Chance 5-10% Excessive Rainfall',
          '_override_lock_': OVERRIDE_LOCK,
          'combinableSegments': True,
          'includeAll': True,
          'allowAreaChange': False,
          'allowTimeChange': False,
          'expirationTime': (-30, 30),
          'hazardConflictList': [],
          'ugcType': 'zone',
          'ugcLabel': 'name',
          #'hazardClipArea' : 'cwa',
          'inclusionFractionTest' : True,
          'inclusionFraction': 0.1,
          'defaultDuration': 8 * HOURS,
          'durationIncrement': 60,
          'allowOverlappingPolygons': True,
          },
    'Prob_Rainfall.Moderate' : {'headline': 'Moderate Chance 10-15% Excessive Rainfall',
          '_override_lock_': OVERRIDE_LOCK,
          'combinableSegments': True,
          'includeAll': True,
          'allowAreaChange': False,
          'allowTimeChange': False,
          'expirationTime': (-30, 30),
          'hazardConflictList': [],
          'ugcType': 'zone',
          'ugcLabel': 'name',
          #'hazardClipArea' : 'cwa',
          'inclusionFractionTest' : True,
          'inclusionFraction': 0.1,
          'defaultDuration': 8 * HOURS,
          'durationIncrement': 60,
          'allowOverlappingPolygons': True,
          },
    'Prob_Rainfall.High' : {'headline': 'High Chance >15% Excessive Rainfall',
          '_override_lock_': OVERRIDE_LOCK,
          'combinableSegments': True,
          'includeAll': True,
          'allowAreaChange': False,
          'allowTimeChange': False,
          'expirationTime': (-30, 30),
          'hazardConflictList': [],
          'ugcType': 'zone',
          'ugcLabel': 'name',
          #'hazardClipArea' : 'cwa',
          'inclusionFractionTest' : True,
          'inclusionFraction': 0.1,
          'defaultDuration': 8 * HOURS,
          'durationIncrement': 60,
          'allowOverlappingPolygons': True,
          },
    
    ################
    # WFO Prob Hazards           
    'Prob_Tornado' : {
              'headline': 'Probabilistic Tornado',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              #'durationChoiceList': [str(i)+" min" for i in range(15, 241, 15)],
              'durationChoiceList': [str(i)+" min" for i in range(1, 241, 1)],
              'defaultDuration': 45 * MINUTES,
              #'durationIncrement': 15,
              'durationIncrement': 1,
              'hatchingStyle': "NONE",
              'hazardConflictList': [],
              'pointBased': False,
              'ugcType': 'county',
              'ugcLabel': '',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest': True,
              'inclusionFraction': 0.1,
              'inclusionAreaTest' : True,
              'inclusionAreaInSqKm' : 1.0,
              'allowUntilFurtherNotice': True,
              'allowAnyStartTime': True,
              'modifyRecommenders': {
                                     'SwathRecommender': [ 'geometry', 'visualFeature', 'timeRange', 'status' ]
                                     },
              'allowOverlappingPolygons': True,
              },
    'Prob_Severe' : {
              'headline': 'Probabilistic Severe',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              #'durationChoiceList': [str(i)+" min" for i in range(15, 241, 15)],
              'durationChoiceList': [str(i)+" min" for i in range(1, 241, 1)],
              'defaultDuration': 45 * MINUTES,
              #'durationIncrement': 15,
              'durationIncrement': 1,
              'hatchingStyle': "NONE",
              'hazardConflictList': [],
              'pointBased': False,
              'ugcType': 'county',
              'ugcLabel': '',
              'hazardClipArea' : 'cwa',
              'inclusionFractionTest': True,
              'inclusionFraction': 0.1,
              'inclusionAreaTest' : True,
              'inclusionAreaInSqKm' : 1.0,
              'allowUntilFurtherNotice': False,
              'allowAnyStartTime': True,
              'modifyRecommenders': {
                                     'SwathRecommender': [ 'geometry', 'visualFeature', 'timeRange', 'status' ]
                                     },
              'allowOverlappingPolygons': True,
              },
    ################
    # Aviation Hazards
    'SIGMET.W' : {
              'headline': 'Aviation SIGMET',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'inclusionFractionTest': True,
              'inclusionFraction': 0.1,
              'defaultDuration': 6 * HOURS, #6 hours
              'durationIncrement': 60,
              },
    'SIGMET.Convective' : {
              'headline': 'Aviation Convective SIGMET',
              '_override_lock_': OVERRIDE_LOCK,
              'combinableSegments': True,
              'includeAll': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'ugcType': 'zone',
              'ugcLabel': 'name',
              'inclusionFractionTest': True,
              'inclusionFraction': 0.1,
              'defaultDuration': 2 * HOURS, #6 hours
              'durationIncrement': 60,
              'modifyRecommenders': {
                                     'LineAndPointTool': [ 'geometry', 'visualFeature' ]
                                     },              
              },                  
    }
