# Notes:  expirationTime is a tuple (beforeMinutes, afterMinutes)
#         hazardConflictList is a list of hazard types which conflict with the
#                            given hazard type.
#         hazardHatchArea represents the area type that a hazard geometry will
#                         be translated into when the hazard is issued. For example,
#                         A WS.W polygon will be translated into a collection of
#                         zones in the associated WSW when issued. 
#                         An FA.A will be translated into a 
#                         collection of counties in the associated FFA when issued.
#                         Some possible values include: county, zone, polygon. 
#                         These are the names of the corresponding tables
#                         in the maps db.
#                         Polygon is used when the polygon will represent the
#                         warned area in the associated product, as is the case
#                         with a TO.W. 
#         hazardHatchLabel The label field to associate with the hazardHatchArea. 
#                          This corresponds to the label field associated with
#                          the maps db table which backs the hatch area. If
#                          hatch area is Polygon, then label field does not apply.
#      inclusionPercentage The minimum percentage a hazard polygon must cover a UGC
#                          area before the UGC can be included in the UGC list.
#            inclusionTest True - perform inclusion test
#                          False - do not perform inclusion test
#                          If this attribute is omitted, then inclusion testing will not
#                          be performed.
#         hazardClipArea   The area, usually hsa or cwa, to restrict hazard geometries to.
#         hazardPointLimit The maximum number of vertices allowed for the hazard type. Excluding
#                          this field means that there is no point limit.
#         durationChoiceList Optional parameter. If not specified, the hazard type will use
#                           an absolute time selector for hazard event end time. If it is
#                           specified, it must be a list of one or more possible durations, 
#                           each of the form "num days", "num hours", "num minutes", or any
#                           combination of the three as long as it is ordered from largest
#                           to smallest unit, i.e. "2 days, 4 hours" is fine, but "4 hours,
#                           2 days" is not. The num must be a positive integer in each case.
#                           The "day" unit may be represented by "d", "day", or "days"; the
#                           "hour" unit by "h", "hr", "hrs", "hour", or "hours"; and the
#                           "minute" unit by "m", "mn", "min", "mins", "minute", or "minutes".
#                           Some examples of valid entries are "5 min", "20 minutes", "45m",
#                           "1 hr", "1h 30m" "1 hour, 45 minutes", "4 hrs", "1 day", "1d 12h",
#                           "2 days", "2 days, 240 minutes", and "3d 5h 20m".
#         defaultDuration   represents the default time duration for this hazard upon
#                           creation.  In milliseconds. (3600000 ms/hour, 60000 ms/minute)
#         durationIncrement represents the increment when setting the duration directly. 
#                           In minutes.
#         allowUntilFurtherNotice if True, the endTime of the hazard and/or the fallBelow
#                           time of the hazard can be set to "Until Further Notice".
#                           If entry is absent, then allowUntilFurtherNotice is False.
#                           Currently by policy only hazards in the FLW_FLS products use
#                           "Until Further Notice"

HOURS = 3600000
MINUTES = 60000
HazardTypes = {
    'AF.Y' : {'headline': 'ASHFALL ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['AF.W'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS, # 8 hours
              'durationIncrement': 60, 
              },
    'AF.W' : {'headline': 'ASHFALL WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['AF.Y'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS, # 8 hours
              'durationIncrement': 60, 
              },
    'AQ.Y' : {'headline': 'AIR QUALITY ALERT',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['AS.O', 'AS.Y'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'AS.O' : {'headline': 'AIR STAGNATION OUTLOOK',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['AQ.Y', 'AS.Y'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'AS.Y' : {'headline': 'AIR STAGNATION ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['AQ.Y', 'AS.O'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'BH.S' : {'headline': 'BEACH HAZARD STATEMENT',   
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['HU.A', 'TR.A', 'TY.A', 'CF.Y', 'CF.W', 'CF.A', 'SS.A', 'SS.W'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'BW.Y' : {'headline': 'BRISK WIND ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['GL.W', 'SR.W', 'HF.W', 'TR.A', 'TR.W', 'HU.A', 'HU.W', 'SC.Y', 'SW.Y', 'SE.W', 'RB.Y', 'SI.Y'],
              'hazardHatchArea': 'marinezones', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'marinezones',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'BZ.A' : {'headline' : 'BLIZZARD WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['LE.A', 'WS.A', 'BZ.W', 'IS.W', 'LE.W', 'WS.W', 'WW.Y', 'LE.Y', 'ZR.Y'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'BZ.W' : {'headline' : 'BLIZZARD WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['BZ.A', 'LE.A', 'WS.A', 'IS.W', 'LE.W', 'WS.W', 'WW.Y', 'LE.Y', 'ZR.Y'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'CF.A' : {'headline': 'COASTAL FLOOD WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['CF.W', 'CF.Y', 'HU.A', 'HU.W', 'SS.A', 'SS.W', 'TR.A', 'TY.A', 'TR.W'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazrdClipArea': 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'CF.W' : {'headline': 'COASTAL FLOOD WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['CF.A', 'CF.Y', 'HU.W', 'SS.A', 'SS.W', 'TR.W', 'TY.W'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'CF.Y' : {'headline': 'COASTAL FLOOD ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['CF.W', 'CF.A', 'HU.W', 'SS.A', 'SS.W', 'TR.W', 'TY.W'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea': 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'CF.S' : {'headline': '',   # No headline for this VTEC
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['HU.A', 'TR.A', 'TY.A', 'CF.Y', 'CF.W', 'CF.A', 'SS.A', 'SS.W'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'DS.W' : {'headline': 'DUST STORM WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['DU.Y'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'DU.Y' : {'headline': 'BLOWING DUST ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['DS.W'],
              'hazardHatchArea': 'zone',
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
             'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'EC.A' : {'headline': 'EXTREME COLD WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['WC.A', 'EC.W', 'WC.W'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'EC.W' : {'headline': 'EXTREME COLD WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['EC.A', 'WC.A', 'WC.W', 'WC.Y'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'EH.A' : {'headline': 'EXCESSIVE HEAT WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['EH.W', 'HT.Y'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'EH.W' : {'headline': 'EXCESSIVE HEAT WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['EH.A', 'HT.Y'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'EW.W' : {'headline': 'EXTREME WIND WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': False,
              'expirationTime': (-10, 10),
              'hazardConflictList': ['TO.W', 'SV.W'],
              'hazardHatchArea': 'polygon', 
              'hazardHatchLabel': '',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 30 * MINUTES,
              'durationIncrement': 1, 
              },
    'FA.A' : {'headline': 'AREAL FLOOD WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['FF.A'],
              'hazardHatchArea': 'county',
              'hazardHatchLabel': 'countyName',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : False,
              'inclusionPercentage': 0.1,
              'replacedBy': ['FA.W', 'FA.Y'],
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'FA.W' : {'headline': 'AREAL FLOOD WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-10, 10),
              'hazardConflictList': [],              
              'hazardHatchArea': 'polygon',
              'hazardHatchLabel': '',
              'hazardClipArea' : 'cwa',
              'replacedBy': ['FA.Y'],
              'hazardPointLimit': 20,
              'durationChoiceList': [ "60 min", "90 min", "120 min", "3 hrs", "6 hrs", "9 hrs", "12 hrs", "24 hrs", "1 day 12 hrs", "2 days", "2 days 12 hrs", "3 days", "4 days", "5 days", "6 days", "7 days" ],
              'defaultDuration': 3 * HOURS,
              'durationIncrement': 15,
              'allowUntilFurtherNotice': True, 
              },
    'FA.Y' : {'headline': 'AREAL FLOOD ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-10, 10),
              'hazardHatchArea': 'polygon',
              'hazardHatchLabel': '',
              'hazardClipArea' : 'cwa',
              'hazardConflictList': [],              
              'hazardPointLimit': 20,
              'replacedBy': ['FA.W'],
              'durationChoiceList': [ "60 min", "120 min", "3 hrs", "3 hrs 30 min", "4 hrs", "4 hrs 30 min", "5 hrs", "5 hrs 30 min", "6 hrs", "7 hrs", "8 hrs", "9 hrs", "10 hrs", "11 hrs", "12 hrs", "24 hrs", "1 day 12 hrs", "2 days", "2 days 12 hrs" ],
              'defaultDuration': 3 * HOURS,
              'durationIncrement': 15, 
              'allowUntilFurtherNotice': True, 
              },
    'FF.A' : {'headline': 'FLASH FLOOD WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['FA.A'],
              'hazardHatchArea': 'county',
              'hazardHatchLabel': 'countyName',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : False,
              'inclusionPercentage': 0.1,
              'replacedBy': ['FF.W.Convective', 'FF.W.NonConvective'],
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              'hazardTypeFirstRecommender':'DamBreakFloodRecommender',
              },
    'FF.W.BurnScar' : {
              'headline': 'FLASH FLOOD WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-10, 10),
              'hazardConflictList': [],
              'hazardHatchArea': 'polygon',
              'hazardHatchLabel': '',
              'hazardClipArea' : 'cwa',
              'hazardPointLimit' : 20,
              'defaultDuration': 3 * HOURS,
              'durationIncrement': 15, 
              'hazardTypeFirstRecommender':'BurnScarFloodRecommender',
              },
    'FF.W.Convective' : {
              'headline': 'FLASH FLOOD WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-10, 10),
              'hazardConflictList': [],
              'hazardHatchArea': 'polygon',
              'hazardHatchLabel': '',
              'hazardClipArea' : 'cwa',
              'hazardPointLimit': 20,
              'durationChoiceList': [ "60 min", "90 min", "120 min", "2 hrs 30 min", "3 hrs", "3 hrs 30 min", "4 hrs", "4 hrs 30 min", "5 hrs", "5 hrs 30 min", "6 hrs", "6 hrs 30 min", "7 hrs", "7 hrs 30 min", "8 hrs" ],
              'defaultDuration': 1 * HOURS,
              'durationIncrement': 15,
              'hazardTypeFirstRecommender':'StormTrackTool',
              },
    'FF.W.NonConvective' : {
              'headline': 'FLASH FLOOD WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-10, 10),
              'hazardConflictList': [],
              'hazardHatchArea': 'polygon',
              'hazardHatchLabel': '',
              'hazardClipArea' : 'cwa',
              'hazardPointLimit' : 20,
              'durationChoiceList': [ "60 min", "90 min", "120 min", "3 hrs", "6 hrs", "9 hrs", "12 hrs", "24 hrs", "1 day 12 hrs", "2 days", "2 days 12 hrs", "3 days", "4 days", "5 days", "6 days", "7 days" ],
              'defaultDuration': 3 * HOURS,
              'durationIncrement': 15, 
              'hazardTypeFirstRecommender':'DamBreakFloodRecommender',
              },
    'FG.Y' : {'headline': 'DENSE FOG ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'FL.A' : {'headline': 'FLOOD WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'hazardHatchArea': 'county',
              'hazardHatchLabel': 'countyName',
              'hazardClipArea' : 'cwa',
              'replacedBy': ['FL.W', 'FL.Y'],
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              'hazardTypeFirstRecommender':'RiverFloodRecommender',
              },
    'FL.W' : {'headline': 'FLOOD WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'hazardHatchArea': 'county',
              'hazardHatchLabel': 'countyName',
              'hazardClipArea' : 'cwa',
              'replacedBy': ['FL.Y'],
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              'allowUntilFurtherNotice': True, 
              'hazardTypeFirstRecommender':'RiverFloodRecommender',
              },
    'FL.Y' : {'headline': 'FLOOD ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'hazardHatchArea': 'county',
              'hazardHatchLabel': 'countyName',
              'hazardClipArea' : 'cwa',
              'replacedBy': ['FL.W'],
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              'allowUntilFurtherNotice': True, 
              'hazardTypeFirstRecommender':'RiverFloodRecommender',
              },
    'FR.Y' : {'headline': 'FROST ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['FZ.A', 'FZ.W', 'HZ.W', 'HZ.A'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'FW.A' : {'headline': 'FIRE WEATHER WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['FW.W'],
              'hazardHatchArea': 'firewxzones', 
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'firewxzones',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'FW.W' : {'headline': 'RED FLAG WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['FW.A'],
              'hazardHatchArea': 'firewxzones', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'firewxzones',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'FZ.A' : {'headline': 'FREEZE WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['FZ.W', 'FR.Y', 'HZ.W', 'HZ.A'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'FZ.W' : {'headline': 'FREEZE WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['FZ.A', 'FR.Y', 'HZ.W', 'HZ.A'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'GL.A' : {'headline': 'GALE WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['SR.W', 'HF.W','TR.A', 'TR.W', 'HU.A', 'HU.W','SE.W', 'GL.W', 'SR.A', 'HF.A', 'SE.A', 'TY.A', 'TY.W'],
              'hazardHatchArea': 'marinezones', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'marinezones',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'GL.W' : {'headline': 'GALE WARNING',            
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList':  ['SR.W', 'HF.W', 'BW.Y', 'TR.W', 'HU.W', 'SC.Y', 'SW.Y', 'SE.W', 'RB.Y', 'SI.Y', 'GL.A', 'SE.A', 'TY.W'],
              'hazardHatchArea': 'marinezones', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'marinezones',
              'defaultDuration': 8 * 360000,
              'durationIncrement': 60, 
              },
    'HF.A' : {'headline': 'HURRICANE FORCE WIND WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['TR.A', 'TR.W', 'HU.A', 'HU.W', 'GL.A', 'SR.A', 'HF.W', 'SE.A', 'TY.A', 'TY.W'],
              'hazardHatchArea': 'marinezones', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'marinezones',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'HF.W' : {'headline': 'HURRICANE FORCE WIND WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList':['GL.W', 'SR.W', 'BW.Y', 'TR.A', 'TR.W', 'HU.A', 'HU.W', 'SC.Y', 'SW.Y', 'SE.W', 'RB.Y', 'SI.Y', 'GL.A', 'SR.A', 'HF.A', 'SE.A', 'TY.W', 'TY.A'],
              'hazardHatchArea': 'marinezones', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'marinezones',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'HT.Y' : {'headline': 'HEAT ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['EH.A', 'EH.W'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'HU.A' : {'headline': 'HURRICANE WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': False,
              'expirationTime': (-30, 30),
              'hazardConflictList':['TR.A', 'HU.W', 'GL.A', 'SR.A', 'HF.W', 'SE.A','CF.S', 'CF.A', 'HW.A' ],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'HU.W' : {'headline': 'HURRICANE WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': False,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['GL.W', 'SR.W', 'HF.W', 'BW.Y', 'TR.A', 'TR.W', 'HU.A', 'SC.Y', 'SW.Y', 'SE.W', 'RB.Y', 'SI.Y', 'GL.A', 'SR.A', 'HF.A', 'SE.A', 'CF.W', 'CF.A', 'CF.Y', 'CF.S', 'SU.W', 'SU.Y','HW.W', 'WI.Y','HW.A', 'LW.Y'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'HW.A' : {'headline': 'HIGH WIND WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['HW.W', 'LW.Y', 'WI.Y', 'TR.A', 'TR.W', 'HU.A', 'HU.W', 'TY.A', 'TY.W'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'HW.W' : {'headline': 'HIGH WIND WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['HW.A', 'LW.Y', 'WI.Y', 'TR.A', 'HU.A', 'TY.A', 'TR.W', 'HU.W', 'TY.W'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'HY.O' : {'headline': 'HYDROLOGIC OUTLOOK',  
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': False,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'hazardHatchArea': 'county', 
              'hazardHatchLabel': 'countyName',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'HY.S' : {'headline': 'FORECAST INFORMATION',  # No headline for this VTEC
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [], #['FL.W', 'FL.Y', 'FL.A'],
              'hazardHatchArea': 'county',
              'hazardHatchLabel': 'countyName',
              'replacedBy': ['FL.A', 'FL.Y', 'FL.W'],
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'HZ.A' : {'headline': 'HARD FREEZE WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['FZ.W', 'FR.Y', 'FZ.A', 'HZ.W'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'HZ.W' : {'headline': 'HARD FREEZE WARNING',  
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['FZ.A', 'FR.Y', 'HZ.A', 'FZ.W'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'IS.W' : {'headline': 'ICE STORM WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['BZ.A', 'LE.A', 'WS.A', 'BZ.W', 'WS.W', 'LE.W', 'WW.Y', 'LE.Y', 'ZR.Y'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'LE.A' : {'headline': 'LAKE EFFECT SNOW WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['BZ.A', 'WS.A', 'BZ.W', 'IS.W', 'WS.W', 'LE.W', 'WW.Y', 'LE.Y', 'ZR.Y'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'LE.W' : {'headline': 'LAKE EFFECT SNOW WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['BZ.A', 'LE.A', 'WS.A', 'BZ.W', 'IS.W', 'WS.W', 'WW.Y', 'LE.Y', 'ZR.Y'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'LE.Y' : {'headline': 'LAKE EFFECT SNOW ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['BZ.A', 'LE.A', 'WS.A', 'BZ.W', 'IS.W', 'LE.W', 'WS.W', 'WW.Y', 'ZR.Y'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'LO.Y' : {'headline': 'LOW WATER ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'LS.A' : {'headline': 'LAKESHORE FLOOD WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['LS.W', 'LS.Y'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'LS.W' : {'headline': 'LAKESHORE FLOOD WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['LS.A', 'LS.Y'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'LS.Y' : {'headline': 'LAKESHORE FLOOD ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['LS.A', 'LS.W'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'LW.Y' : {'headline': 'LAKE WIND ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList':  ['HW.A', 'HW.W', 'WI.Y', 'TR.A', 'HU.A', 'TY.A', 'TR.W', 'HU.W', 'TY.W'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'MA.S' : {'headline': '',  # No headline for this VTEC
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'hazardHatchArea': '', 
              'hazardHatchLabel': '',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'MA.W' : {'headline': 'SPECIAL MARINE WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': False,
              'expirationTime': (-10, 10),
              'hazardConflictList': [],
              'hazardHatchArea': 'polygon', 
              'hazardHatchLabel': '',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'marinezones',
              'defaultDuration': 30 * MINUTES,
              'durationIncrement': 15, 
              },
    'MF.Y' : {'headline': 'DENSE FOG ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'hazardHatchArea': 'marinezones', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'marinezones',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              }, # Marine Fog
    'MH.Y' : {'headline': 'ASHFALL ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['MH.W'],
              'hazardHatchArea': 'marinezones', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'marinezones',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              }, # Marine Ashfall
    'MS.Y' : {'headline': 'DENSE SMOKE ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'hazardHatchArea': 'marinezones', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'marinezones',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              }, # Marine Smoke
    'RB.Y' : {'headline': 'SMALL CRAFT ADVISORY FOR ROUGH BAR',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList':  ['SR.W', 'HF.W', 'BW.Y', 'TR.W', 'HU.W', 'SE.W', 'GL.W', 'TY.W'],
              'hazardHatchArea': 'marinezones', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'marinezones',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'SC.Y' : {'headline': 'SMALL CRAFT ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList':  ['SR.W', 'HF.W', 'BW.Y', 'TR.W', 'HU.W', 'SE.W', 'GL.W', 'TY.W'],
              'hazardHatchArea': 'marinezones', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'marinezones',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'SE.A' : {'headline': 'HAZARDOUS SEAS WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['SE.W', 'GL.W', 'SR.W', 'HF.W', 'BW.Y', 'TR.W', 'HU.W', 'GL.A', 'SR.A', 'HF.A', 'TR.A',  'HU.A', 'TY.W', 'TY.A'],
              'hazardHatchArea': 'marinezones', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'marinezones',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'SE.W' : {'headline': 'HAZARDOUS SEAS WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['GL.W', 'SR.W', 'BW.Y', 'TR.W', 'HU.W', 'SC.Y', 'SW.Y', 'RB.Y', 'SI.Y', 'GL.A', 'HF.W', 'SE.A', 'TY.W'],
              'hazardHatchArea': 'marinezones', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'marinezones',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'SI.Y' : {'headline': 'SMALL CRAFT ADVISORY FOR WINDS',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['GL.W', 'SE.W', 'SR.W', 'HF.W', 'BW.Y', 'TR.W', 'HU.W', 'TY.W'],
              'hazardHatchArea': 'marinezones', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'marinezones',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'SM.Y' : {'headline': 'DENSE SMOKE ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': [],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'SR.A' : {'headline': 'STORM WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList':['SR.W', 'HF.W', 'BW.Y', 'TR.W', 'HU.W', 'GL.A', 'SR.A', 'HF.A', 'TR.A',  'HU.A', 'TY.W', 'TY.A'],
              'hazardHatchArea': 'marinezones', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'marinezones',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'SR.W' : {'headline': 'STORM WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['GL.W', 'HF.W', 'BW.Y', 'TR.W', 'HU.W', 'TY.W', 'SC.Y', 'SW.Y', 'SE.W', 'SE.A', 'RB.Y', 'SI.Y', 'GL.A', 'SR.A'],
              'hazardHatchArea': 'marinezones', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'marinezones',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'SU.W' : {'headline': 'HIGH SURF WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['SU.Y', 'HU.W', 'TR.W', 'TY.W'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'SU.Y' : {'headline': 'HIGH SURF ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['SU.W', 'HU.W', 'TR.W', 'TY.W'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },             
    'SV.A' : {'headline': 'SEVERE THUNDERSTORM WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['TO.A'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'SV.W' : {'headline': 'SEVERE THUNDERSTORM WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': False,
              'expirationTime': (-10, 10),
              'hazardConflictList': [],
              'hazardHatchArea': 'polygon', 
              'hazardHatchLabel': '',
              'hazardClipArea' : 'cwa',
              'defaultDuration': 30 * MINUTES,
              'durationIncrement': 15, 
              },
    'SW.Y' : {'headline': 'SMALL CRAFT ADVISORY FOR HAZARDOUS SEAS',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['SE.W', 'GL.W', 'SR.W', 'HF.W', 'BW.Y', 'TR.W', 'HU.W', 'TY.W'],
              'hazardHatchArea': 'marinezones', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'marinezones',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'TO.A' : {'headline': 'TORNADO WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['SV.A'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'TO.W' : {'headline': 'TORNADO WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': False,
              'allowAreaChange': False,
              'allowTimeChange': False,
              'expirationTime': (-10, 10),
              'hazardConflictList': [],
              'hazardHatchArea': 'polygon', 
              'hazardHatchLabel': '',
              'hazardClipArea' : 'cwa',
              'defaultDuration': 30 * MINUTES,
              'durationIncrement': 15, 
              },
    'TR.A' : {'headline': 'TROPICAL STORM WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': False,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['HU.A', 'HU.W', 'TY.A', 'TY.W', 'TR.W', 'HW.A', 'GL.A', 'SE.A', 'SR.A', 'SR.W', 'HF.W', 'CF.S', 'CF.A'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'TR.W' : {'headline': 'TROPICAL STORM WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': False,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['GL.W', 'SR.W', 'HF.W', 'BW.Y', 'TR.A', 'TY.W', 'HU.W', 'SC.Y', 'SW.Y', 'SE.W', 'RB.Y', 'SI.Y', 'GL.A', 'SR.A', 'HF.A', 'SE.A', 'CF.W', 'CF.A', 'CF.Y', 'CF.S', 'SU.W', 'SU.Y', 'HW.W', 'WI.Y','HW.A', 'LW.Y'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'TS.A' : {'headline': 'TSUNAMI WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['TS.W'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'TS.W' : {'headline': 'TSUNAMI WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['TS.A'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'TY.A' : {'headline': 'TYPHOON WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': False,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['TR.A', 'TY.W', 'GL.A', 'SR.A', 'HF.W', 'SE.A','CF.S', 'CF.A', 'HW.A' ],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'TY.W' : {'headline': 'TYPHOON WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': False,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['GL.W', 'SR.W', 'HF.W', 'BW.Y', 'TR.A', 'TR.W', 'TY.A', 'SC.Y', 'SW.Y', 'SE.W', 'RB.Y', 'SI.Y', 'GL.A', 'SR.A', 'HF.A', 'SE.A', 'CF.W', 'CF.A', 'CF.Y', 'CF.S', 'SU.W', 'SU.Y','HW.W', 'WI.Y','HW.A', 'LW.Y'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',              
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'UP.A' : {'headline': 'HEAVY FREEZING SPRAY WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['UP.W', 'UP.Y'],
              'hazardHatchArea': 'marinezones', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'marinezones',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'UP.W' : {'headline': 'HEAVY FREEZING SPRAY WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['UP.A', 'UP.Y'],
              'hazardHatchArea': 'marinezones', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'cwa',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'UP.Y' : {'headline': 'FREEZING SPRAY ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList':['UP.A', 'UP.W'],
              'hazardHatchArea': 'marinezones', 
              'hazardHatchLabel': 'name',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'hazardClipArea' : 'marinezones',
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'WC.A' : {'headline': 'WIND CHILL WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['WC.Y', 'WC.W'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'WC.W' : {'headline': 'WIND CHILL WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['WC.A', 'WC.Y'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'WC.Y' : {'headline': 'WIND CHILL ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['WC.A', 'WC.W'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'WI.Y' : {'headline': 'WIND ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['HW.A', 'HW.W', 'LW.Y', 'TR.A', 'HU.A', 'TY.A', 'TR.W', 'HU.W', 'TY.W'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
             },
    'WS.A' : {'headline': 'WINTER STORM WATCH',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['BZ.A', 'LE.A', 'BZ.W', 'IS.W', 'WS.W', 'LE.W', 'WW.Y', 'LE.Y', 'ZR.Y'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'WS.W' : {'headline': 'WINTER STORM WARNING',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['BZ.A', 'LE.A', 'WS.A', 'BZ.W', 'IS.W', 'LE.W', 'WW.Y', 'LE.Y', 'ZR.Y'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'WW.Y' : {'headline': 'WINTER WEATHER ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['BZ.A', 'LE.A', 'WS.A', 'BZ.W', 'IS.W', 'WS.W', 'LE.W', 'LE.Y', 'ZR.Y'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'ZF.Y' : {'headline': 'FREEZING FOG ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['FG.Y'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
              },
    'ZR.Y' : {'headline': 'FREEZING RAIN ADVISORY',
              '_override_lock_': ['headline','combinableSegments', 'allowAreaChange', 'allowTimeChange', 'expirationTime', True],
              'combinableSegments': True,
              'allowAreaChange': True,
              'allowTimeChange': True,
              'expirationTime': (-30, 30),
              'hazardConflictList': ['BZ.A', 'LE.A', 'WS.A', 'BZ.W', 'IS.W', 'WS.W', 'LE.W', 'WW.Y', 'LE.Y'],
              'hazardHatchArea': 'zone', 
              'hazardHatchLabel': 'name',
              'hazardClipArea' : 'cwa',
              'inclusionTest' : True,
              'inclusionPercentage': 0.1,
              'defaultDuration': 8 * HOURS,
              'durationIncrement': 60, 
             },
    }
