/**
 * This software was developed and / or modified by the
 * National Oceanic and Atmospheric Administration (NOAA), 
 * Earth System Research Laboratory (ESRL), 
 * Global Systems Division (GSD), 
 * Information Services Branch (ISB)
 * 
 * Address: Department of Commerce Boulder Labs, 325 Broadway, Boulder, CO 80305
 */
package gov.noaa.gsd.viz.hazards.hazarddetail;

import gov.noaa.gsd.common.utilities.ICurrentTimeProvider;
import gov.noaa.gsd.viz.hazards.hazarddetail.HazardDetailPresenter.Command;
import gov.noaa.gsd.viz.hazards.hazarddetail.HazardDetailPresenter.DisplayableEventIdentifier;
import gov.noaa.gsd.viz.mvp.widgets.IChoiceStateChanger;
import gov.noaa.gsd.viz.mvp.widgets.ICommandInvoker;
import gov.noaa.gsd.viz.mvp.widgets.IStateChanger;

import java.util.Map;

import com.google.common.collect.ImmutableList;
import com.raytheon.uf.common.time.TimeRange;

/**
 * Description: Interface describing the methods that must be implemented by a
 * class that functions as a hazard detail view.
 * 
 * <pre>
 * 
 * SOFTWARE HISTORY
 * Date         Ticket#    Engineer     Description
 * ------------ ---------- ------------ --------------------------
 * May 09, 2014    2925    Chris.Golden Initial creation.
 * Jun 25, 2014    4009    Chris.Golden Added code to cache extra data held by
 *                                      metadata megawidgets between view
 *                                      instantiations.
 * Jul 03, 2014    3512    Chris.Golden Added code to allow a duration selector
 *                                      to be displayed instead of an absolute
 *                                      date/time selector for the end time of
 *                                      a hazard event.
 * Aug 15, 2014    4243    Chris.Golden Added notifier invoker fetcher, to
 *                                      allow the invoker used to receive
 *                                      notifications generated by notifier
 *                                      megawidgets.
 * Sep 16, 2014    4753    Chris.Golden Changed event script running to include
 *                                      mutable properties.
 * </pre>
 * 
 * @author Chris.Golden
 * @version 1.0
 */
public interface IHazardDetailView {

    /**
     * Initialize the view.
     * 
     * @param hazardCategories
     *            List of hazard categories.
     * @param minVisibleTime
     *            Minimum visible time to be shown in the time widgets.
     * @param maxVisibleTime
     *            Maximum visible time to be shown in the time widgets.
     * @param currentTimeProvider
     *            Current time provider, used for the time range widgets.
     * @param extraDataForEventIdentifiers
     *            Map pairing event identifiers with any extra data they may
     *            have used in previous view instantiations, allowing such data
     *            to persist between different views.
     */
    public void initialize(
            ImmutableList<String> hazardCategories,
            long minVisibleTime,
            long maxVisibleTime,
            ICurrentTimeProvider currentTimeProvider,
            Map<String, Map<String, Map<String, Object>>> extraDataForEventIdentifiers);

    /**
     * Get the visible time range state changer. The identifier is ignored.
     * 
     * @return Visible time range state changer.
     */
    public IStateChanger<String, TimeRange> getVisibleTimeRangeChanger();

    /**
     * Get the selected event state changer. The identifier is ignored.
     * 
     * @return Selected event state changer.
     */
    public IChoiceStateChanger<String, String, String, DisplayableEventIdentifier> getVisibleEventChanger();

    /**
     * Get the category state changer. The identifier is that of the hazard
     * event.
     * 
     * @return Category state changer.
     */
    public IChoiceStateChanger<String, String, String, String> getCategoryChanger();

    /**
     * Get the type state changer. The identifier is that of the hazard event.
     * 
     * @return Type state changer.
     */
    public IChoiceStateChanger<String, String, String, String> getTypeChanger();

    /**
     * Get the time range state changer. The identifier is that of the hazard
     * event.
     * 
     * @return Time range state changer.
     */
    public IStateChanger<String, TimeRange> getTimeRangeChanger();

    /**
     * Get the duration changer. This is only used to set the choices for
     * possible durations; changes in the chosen duration are handled as time
     * range changes. The identifier is that of the hazard event.
     * 
     * @return Duration changer.
     */
    public IChoiceStateChanger<String, String, String, String> getDurationChanger();

    /**
     * Get the metadata state changer. The qualifier is the identifier of the
     * hazard event, while the identifier is that of the metadata.
     * 
     * @return Metadata state changer.
     */
    public IMetadataStateChanger getMetadataChanger();

    /**
     * Get the notifier invoker. The identifier is that of the hazard event
     * coupled with that of the notifier.
     * 
     * @return Notifier invoker.
     */
    public ICommandInvoker<EventScriptInfo> getNotifierInvoker();

    /**
     * Get the button invoker. The identifier is the command.
     * 
     * @return Button invoker.
     */
    public ICommandInvoker<Command> getButtonInvoker();
}
