/**
 * This software was developed and / or modified by the
 * National Oceanic and Atmospheric Administration (NOAA), 
 * Earth System Research Laboratory (ESRL), 
 * Global Systems Division (GSD), 
 * Information Services Branch (ISB)
 * 
 * Address: Department of Commerce Boulder Labs, 325 Broadway, Boulder, CO 80305
 */
package gov.noaa.gsd.viz.mvp.widgets;

import java.util.Map;

/**
 * Interface describing the methods that must be implemented by a handler for
 * state changes generated by a {@link IStateChanger}. The generic parameter
 * <code>I</code> provides the type of widget identifier to be used, while
 * <code>S</code> provides the type of state.
 * 
 * <pre>
 * 
 * SOFTWARE HISTORY
 * Date         Ticket#    Engineer     Description
 * ------------ ---------- ------------ --------------------------
 * May 08, 2014    2925    Chris.Golden Initial creation.
 * Jun 30, 2014    3512    Chris.Golden Added method that allows notification
 *                                      of multiple simultaneous state
 *                                      changes.
 * </pre>
 * 
 * @author Chris.Golden
 * @version 1.0
 */
public interface IStateChangeHandler<I, S> {

    // Public Methods

    /**
     * Receive notification that the specified state was changed.
     * 
     * @param identifier
     *            Identifier of the state that was changed. This may be
     *            <code>null</code> if this object only handles one particular
     *            state's changes.
     * @param value
     *            New value for the specified state.
     */
    public void stateChanged(I identifier, S value);

    /**
     * Receive notification that the specified states were changed.
     * 
     * @param valuesForIdentifiers
     *            Map pairing state identifiers with their new values.
     */
    public void statesChanged(Map<I, S> valuesForIdentifiers);
}
