#!/bin/csh -f
if ! $?ADE then
  echo Must set an ADE env variable
else
  cd $ADE/AWIPS2_baseline/edexOsgi/build.edex
  ant -f deploy-install.xml -Dwa.to.deploy=$ADE/hazardServices
  #
  #  We want to assume next to last line of /awips2/edex/bin/start.sh contains
  #   export MAX_MEM="1280"
  #
  set startFil = /awips2/edex/bin/start.sh
  grep 'export  *MAX_MEM' $startFil >& /dev/null
  if ( $status == 0 ) exit
  set n = `cat $startFil | wc -l`
  @ n--
  ( head -n $n $startFil ; echo 'export MAX_MEM="1280"' ; tail -n 1 $startFil )\
      > /tmp/startFil.tmp
  cat /tmp/startFil.tmp > $startFil
  rm -f /tmp/startFil.tmp >& /dev/null
  chmod 775 $startFil
endif
