#this file contains metadata about volcanoes, used to populate menus for International SIGMET, AIRMET, and Volcanic Ash Advisory
class VolcanoMetaData:
    
    def volcanoIndicatorsDict(self):
        return {'himawari': 'HIMAWARI', 
                'goes': 'GOES', 
                'poes': 'POES',
                'lightning': 'LIGHTNING', 
                'avo': 'AVO', 
                'kvert': 'KVERT', 
                'pilot': 'PILOT REPORT',
                'radar': 'RADAR', 
                'ship': 'SHIP REPORT', 
                'webcam': 'AVO WEBCAM'
                }
    
    def getVolcanoIndicators(self):
        return [{"identifier": "himawari","displayString": "HIMAWARI"},
                {"identifier": "goes","displayString": "GOES"},
                {"identifier": "poes","displayString": "POES"},
                {"identifier": "lightning","displayString": "LIGHTNING"},                            
                {"identifier": "avo","displayString": "AVO"},
                {"identifier": "kvert","displayString": "KVERT"},
                {"identifier": "pilot","displayString": "PILOT REPORT"},
                {"identifier": "radar","displayString": "RADAR"},
                {"identifier": "ship","displayString": "SHIP REPORT"},
                {"identifier": "webcam","displayString": "AVO WEBCAM"},                                                                                                                                                                                                                                                                                                                                                                                                                
                ]    
    
    def getVolcanoDict(self):
        volcanoDict = {
                       "FUKUJIN": {"volcanoNumber": "284133", "volcanoLatitude": "21.93", "volcanoElevation": "-217", "volcanoSubregion": "Izu, Volcano, and Mariana Islands", "volcanoLongitude": "143.47"},
                       "KASUGA 1": {"volcanoNumber": "284134", "volcanoLatitude": "21.765", "volcanoElevation": "-598", "volcanoSubregion": "Izu, Volcano, and Mariana Islands", "volcanoLongitude": "143.71"},
                       "KASUGA 2": {"volcanoNumber": "284135", "volcanoLatitude": "21.6", "volcanoElevation": "-274", "volcanoSubregion": "Izu, Volcano, and Mariana Islands", "volcanoLongitude": "143.637"},
                       "NW EIFUKU": {"volcanoNumber": "284136", "volcanoLatitude": "21.485", "volcanoElevation": "-1535", "volcanoSubregion": "Izu, Volcano, and Mariana Islands", "volcanoLongitude": "144.043"},
                       "DAIKOKU": {"volcanoNumber": "284137", "volcanoLatitude": "21.324", "volcanoElevation": "-323", "volcanoSubregion": "Izu, Volcano, and Mariana Islands", "volcanoLongitude": "144.194"},
                       "FARALLON DE PAJAROS": {"volcanoNumber": "284140", "volcanoLatitude": "20.538", "volcanoElevation": "360", "volcanoSubregion": "Izu, Volcano, and Mariana Islands", "volcanoLongitude": "144.896"},
                       "AHYI": {"volcanoNumber": "284141", "volcanoLatitude": "20.42", "volcanoElevation": "-75", "volcanoSubregion": "Izu, Volcano, and Mariana Islands", "volcanoLongitude": "145.03"},
                       "SUPPLY REEF": {"volcanoNumber": "284142", "volcanoLatitude": "20.13", "volcanoElevation": "-8", "volcanoSubregion": "Izu, Volcano, and Mariana Islands", "volcanoLongitude": "145.1"},
                       "MAUG ISLANDS": {"volcanoNumber": "284143", "volcanoLatitude": "20.02", "volcanoElevation": "227", "volcanoSubregion": "Izu, Volcano, and Mariana Islands", "volcanoLongitude": "145.22"},
                       "ASUNCION": {"volcanoNumber": "284150", "volcanoLatitude": "19.671", "volcanoElevation": "857", "volcanoSubregion": "Izu, Volcano, and Mariana Islands", "volcanoLongitude": "145.406"},
                       "AGRIGAN": {"volcanoNumber": "284160", "volcanoLatitude": "18.77", "volcanoElevation": "965", "volcanoSubregion": "Izu, Volcano, and Mariana Islands", "volcanoLongitude": "145.67"},
                       "PAGAN": {"volcanoNumber": "284170", "volcanoLatitude": "18.13", "volcanoElevation": "570", "volcanoSubregion": "Izu, Volcano, and Mariana Islands", "volcanoLongitude": "145.8"},
                       "ALAMAGAN": {"volcanoNumber": "284180", "volcanoLatitude": "17.6", "volcanoElevation": "744", "volcanoSubregion": "Izu, Volcano, and Mariana Islands", "volcanoLongitude": "145.83"},
                       "GUGUAN": {"volcanoNumber": "284190", "volcanoLatitude": "17.307", "volcanoElevation": "287", "volcanoSubregion": "Izu, Volcano, and Mariana Islands", "volcanoLongitude": "145.845"},
                       "ZEALANDIA BANK": {"volcanoNumber": "284191", "volcanoLatitude": "16.88", "volcanoElevation": "0", "volcanoSubregion": "Izu, Volcano, and Mariana Islands", "volcanoLongitude": "145.85"},
                       "SARIGAN": {"volcanoNumber": "284192", "volcanoLatitude": "16.708", "volcanoElevation": "538", "volcanoSubregion": "Izu, Volcano, and Mariana Islands", "volcanoLongitude": "145.78"},
                       "SOUTH SARIGAN SEAMOUNT": {"volcanoNumber": "284193", "volcanoLatitude": "16.58", "volcanoElevation": "-184", "volcanoSubregion": "Izu, Volcano, and Mariana Islands", "volcanoLongitude": "145.78"},
                       "ANATAHAN": {"volcanoNumber": "284200", "volcanoLatitude": "16.35", "volcanoElevation": "790", "volcanoSubregion": "Izu, Volcano, and Mariana Islands", "volcanoLongitude": "145.67"},
                       "EAST DIAMANTE": {"volcanoNumber": "284201", "volcanoLatitude": "15.93", "volcanoElevation": "-127", "volcanoSubregion": "Izu, Volcano, and Mariana Islands", "volcanoLongitude": "145.67"},
                       "RUBY": {"volcanoNumber": "284202", "volcanoLatitude": "15.62", "volcanoElevation": "-230", "volcanoSubregion": "Izu, Volcano, and Mariana Islands", "volcanoLongitude": "145.57"},
                       "ESMERALDA BANK": {"volcanoNumber": "284210", "volcanoLatitude": "15", "volcanoElevation": "-43", "volcanoSubregion": "Izu, Volcano, and Mariana Islands", "volcanoLongitude": "145.25"},
                       "NW ROTA-1": {"volcanoNumber": "284211", "volcanoLatitude": "14.601", "volcanoElevation": "-517", "volcanoSubregion": "Izu, Volcano, and Mariana Islands", "volcanoLongitude": "144.775"},
                       "FORECAST SEAMOUNT": {"volcanoNumber": "284220", "volcanoLatitude": "13.4", "volcanoElevation": "0", "volcanoSubregion": "Izu, Volcano, and Mariana Islands", "volcanoLongitude": "143.92"},
                       "SEAMOUNT X": {"volcanoNumber": "284230", "volcanoLatitude": "13.25", "volcanoElevation": "-1230", "volcanoSubregion": "Izu, Volcano, and Mariana Islands", "volcanoLongitude": "144.02"},
                       "BULDIR": {"volcanoNumber": "311010", "volcanoLatitude": "52.35", "volcanoElevation": "656", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "175.911"},
                       "KISKA": {"volcanoNumber": "311020", "volcanoLatitude": "52.103", "volcanoElevation": "1220", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "177.602"},
                       "SEGULA": {"volcanoNumber": "311030", "volcanoLatitude": "52.015", "volcanoElevation": "1160", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "178.136"},
                       "DAVIDOF": {"volcanoNumber": "311040", "volcanoLatitude": "51.97", "volcanoElevation": "328", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "178.33"},
                       "LITTLE SITKIN": {"volcanoNumber": "311050", "volcanoLatitude": "51.95", "volcanoElevation": "1174", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "178.543"},
                       "SEMISOPOCHNOI": {"volcanoNumber": "311060", "volcanoLatitude": "51.93", "volcanoElevation": "1221", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "179.58"},
                       "GARELOI": {"volcanoNumber": "311070", "volcanoLatitude": "51.79", "volcanoElevation": "1573", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-178.794"},
                       "TANAGA": {"volcanoNumber": "311080", "volcanoLatitude": "51.885", "volcanoElevation": "1806", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-178.146"},
                       "TAKAWANGHA": {"volcanoNumber": "311090", "volcanoLatitude": "51.873", "volcanoElevation": "1449", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-178.006"},
                       "BOBROF": {"volcanoNumber": "311100", "volcanoLatitude": "51.91", "volcanoElevation": "738", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-177.438"},
                       "KANAGA": {"volcanoNumber": "311110", "volcanoLatitude": "51.923", "volcanoElevation": "1307", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-177.168"},
                       "MOFFETT": {"volcanoNumber": "311111", "volcanoLatitude": "51.944", "volcanoElevation": "1196", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-176.747"},
                       "GREAT SITKIN": {"volcanoNumber": "311120", "volcanoLatitude": "52.076", "volcanoElevation": "1740", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-176.13"},
                       "KASATOCHI": {"volcanoNumber": "311130", "volcanoLatitude": "52.177", "volcanoElevation": "314", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-175.508"},
                       "KONIUJI": {"volcanoNumber": "311140", "volcanoLatitude": "52.22", "volcanoElevation": "273", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-175.13"},
                       "ATKA": {"volcanoNumber": "311160", "volcanoLatitude": "52.331", "volcanoElevation": "1448", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-174.139"},
                       "KOROVIN": {"volcanoNumber": "311161", "volcanoLatitude": "52.381", "volcanoElevation": "1518", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-174.166"},
                       "SEGUAM": {"volcanoNumber": "311180", "volcanoLatitude": "52.315", "volcanoElevation": "1054", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-172.51"},
                       "AMUKTA": {"volcanoNumber": "311190", "volcanoLatitude": "52.5", "volcanoElevation": "1066", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-171.252"},
                       "CHAGULAK": {"volcanoNumber": "311200", "volcanoLatitude": "52.577", "volcanoElevation": "1142", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-171.13"},
                       "YUNASKA": {"volcanoNumber": "311210", "volcanoLatitude": "52.643", "volcanoElevation": "550", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-170.629"},
                       "HERBERT": {"volcanoNumber": "311220", "volcanoLatitude": "52.742", "volcanoElevation": "1280", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-170.111"},
                       "CARLISLE": {"volcanoNumber": "311230", "volcanoLatitude": "52.894", "volcanoElevation": "1620", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-170.054"},
                       "CLEVELAND": {"volcanoNumber": "311240", "volcanoLatitude": "52.825", "volcanoElevation": "1730", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-169.944"},
                       "TANA": {"volcanoNumber": "311241", "volcanoLatitude": "52.83", "volcanoElevation": "1170", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-169.77"},
                       "ULIAGA": {"volcanoNumber": "311250", "volcanoLatitude": "53.065", "volcanoElevation": "888", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-169.77"},
                       "KAGAMIL": {"volcanoNumber": "311260", "volcanoLatitude": "52.974", "volcanoElevation": "893", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-169.72"},
                       "VSEVIDOF": {"volcanoNumber": "311270", "volcanoLatitude": "53.13", "volcanoElevation": "2149", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-168.693"},
                       "RECHESCHNOI": {"volcanoNumber": "311280", "volcanoLatitude": "53.157", "volcanoElevation": "1984", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-168.539"},
                       "OKMOK": {"volcanoNumber": "311290", "volcanoLatitude": "53.43", "volcanoElevation": "1073", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-168.13"},
                       "BOGOSLOF": {"volcanoNumber": "311300", "volcanoLatitude": "53.93", "volcanoElevation": "150", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-168.03"},
                       "MAKUSHIN": {"volcanoNumber": "311310", "volcanoLatitude": "53.891", "volcanoElevation": "1800", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-166.923"},
                       "AKUTAN": {"volcanoNumber": "311320", "volcanoLatitude": "54.134", "volcanoElevation": "1303", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-165.986"},
                       "WESTDAHL": {"volcanoNumber": "311340", "volcanoLatitude": "54.518", "volcanoElevation": "1654", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-164.65"},
                       "FISHER": {"volcanoNumber": "311350", "volcanoLatitude": "54.65", "volcanoElevation": "1112", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-164.43"},
                       "SHISHALDIN": {"volcanoNumber": "311360", "volcanoLatitude": "54.756", "volcanoElevation": "2857", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-163.97"},
                       "ISANOTSKI": {"volcanoNumber": "311370", "volcanoLatitude": "54.765", "volcanoElevation": "2446", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-163.723"},
                       "ROUNDTOP": {"volcanoNumber": "311380", "volcanoLatitude": "54.8", "volcanoElevation": "1871", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-163.589"},
                       "AMAK": {"volcanoNumber": "311390", "volcanoLatitude": "55.424", "volcanoElevation": "488", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-163.149"},
                       "ADAGDAK": {"volcanoNumber": "311800", "volcanoLatitude": "51.988", "volcanoElevation": "610", "volcanoSubregion": "Aleutian Islands", "volcanoLongitude": "-176.592"},
                       "FROSTY": {"volcanoNumber": "312010", "volcanoLatitude": "55.067", "volcanoElevation": "1728", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-162.835"},
                       "DUTTON": {"volcanoNumber": "312011", "volcanoLatitude": "55.183", "volcanoElevation": "1465", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-162.276"},
                       "EMMONS LAKE": {"volcanoNumber": "312020", "volcanoLatitude": "55.341", "volcanoElevation": "1436", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-162.073"},
                       "PAVLOF": {"volcanoNumber": "312030", "volcanoLatitude": "55.417", "volcanoElevation": "2493", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-161.894"},
                       "PAVLOF SISTER": {"volcanoNumber": "312040", "volcanoLatitude": "55.457", "volcanoElevation": "2142", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-161.854"},
                       "DANA": {"volcanoNumber": "312050", "volcanoLatitude": "55.641", "volcanoElevation": "1354", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-161.214"},
                       "STEPOVAK BAY 2": {"volcanoNumber": "312051", "volcanoLatitude": "55.913", "volcanoElevation": "1323", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-160.041"},
                       "STEPOVAK BAY 3": {"volcanoNumber": "312052", "volcanoLatitude": "55.929", "volcanoElevation": "1555", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-160.002"},
                       "STEPOVAK BAY 4": {"volcanoNumber": "312053", "volcanoLatitude": "55.954", "volcanoElevation": "1557", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-159.954"},
                       "KUPREANOF": {"volcanoNumber": "312060", "volcanoLatitude": "56.011", "volcanoElevation": "1895", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-159.797"},
                       "VENIAMINOF": {"volcanoNumber": "312070", "volcanoLatitude": "56.17", "volcanoElevation": "2507", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-159.38"},
                       "BLACK PEAK": {"volcanoNumber": "312080", "volcanoLatitude": "56.552", "volcanoElevation": "1032", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-158.785"},
                       "ANIAKCHAK": {"volcanoNumber": "312090", "volcanoLatitude": "56.88", "volcanoElevation": "1341", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-158.17"},
                       "YANTARNI": {"volcanoNumber": "312100", "volcanoLatitude": "57.019", "volcanoElevation": "1345", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-157.185"},
                       "CHIGINAGAK": {"volcanoNumber": "312110", "volcanoLatitude": "57.135", "volcanoElevation": "2221", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-156.99"},
                       "KIALAGVIK": {"volcanoNumber": "312120", "volcanoLatitude": "57.203", "volcanoElevation": "1677", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-156.745"},
                       "UGASHIK-PEULIK": {"volcanoNumber": "312130", "volcanoLatitude": "57.751", "volcanoElevation": "1474", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-156.368"},
                       "UKINREK MAARS": {"volcanoNumber": "312131", "volcanoLatitude": "57.832", "volcanoElevation": "91", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-156.51"},
                       "UNNAMED": {"volcanoNumber": "312132", "volcanoLatitude": "57.87", "volcanoElevation": "402", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-155.411"},
                       "MARTIN": {"volcanoNumber": "312140", "volcanoLatitude": "58.172", "volcanoElevation": "1863", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-155.361"},
                       "MAGEIK": {"volcanoNumber": "312150", "volcanoLatitude": "58.195", "volcanoElevation": "2165", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-155.253"},
                       "TRIDENT": {"volcanoNumber": "312160", "volcanoLatitude": "58.236", "volcanoElevation": "1864", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-155.1"},
                       "KATMAI": {"volcanoNumber": "312170", "volcanoLatitude": "58.28", "volcanoElevation": "2047", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-154.963"},
                       "NOVARUPTA": {"volcanoNumber": "312180", "volcanoLatitude": "58.27", "volcanoElevation": "841", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-155.157"},
                       "GRIGGS": {"volcanoNumber": "312190", "volcanoLatitude": "58.354", "volcanoElevation": "2317", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-155.092"},
                       "SNOWY MOUNTAIN": {"volcanoNumber": "312200", "volcanoLatitude": "58.336", "volcanoElevation": "2162", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-154.682"},
                       "DENISON": {"volcanoNumber": "312210", "volcanoLatitude": "58.418", "volcanoElevation": "2287", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-154.449"},
                       "STELLER": {"volcanoNumber": "312220", "volcanoLatitude": "58.43", "volcanoElevation": "2272", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-154.4"},
                       "KUKAK": {"volcanoNumber": "312230", "volcanoLatitude": "58.453", "volcanoElevation": "2043", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-154.355"},
                       "KAGUYAK": {"volcanoNumber": "312250", "volcanoLatitude": "58.608", "volcanoElevation": "901", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-154.028"},
                       "FOURPEAKED": {"volcanoNumber": "312260", "volcanoLatitude": "58.77", "volcanoElevation": "2105", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-153.672"},
                       "DOUGLAS": {"volcanoNumber": "312270", "volcanoLatitude": "58.855", "volcanoElevation": "2140", "volcanoSubregion": "Alaska Peninsula", "volcanoLongitude": "-153.542"},
                       "AUGUSTINE": {"volcanoNumber": "313010", "volcanoLatitude": "59.363", "volcanoElevation": "1252", "volcanoSubregion": "Alaska (southwestern)", "volcanoLongitude": "-153.43"},
                       "ILIAMNA": {"volcanoNumber": "313020", "volcanoLatitude": "60.032", "volcanoElevation": "3053", "volcanoSubregion": "Alaska (southwestern)", "volcanoLongitude": "-153.09"},
                       "REDOUBT": {"volcanoNumber": "313030", "volcanoLatitude": "60.485", "volcanoElevation": "3108", "volcanoSubregion": "Alaska (southwestern)", "volcanoLongitude": "-152.742"},
                       "SPURR": {"volcanoNumber": "313040", "volcanoLatitude": "61.299", "volcanoElevation": "3374", "volcanoSubregion": "Alaska (southwestern)", "volcanoLongitude": "-152.251"},
                       "HAYES": {"volcanoNumber": "313050", "volcanoLatitude": "61.64", "volcanoElevation": "3034", "volcanoSubregion": "Alaska (southwestern)", "volcanoLongitude": "-152.411"},
                       "ST. PAUL ISLAND": {"volcanoNumber": "314010", "volcanoLatitude": "57.18", "volcanoElevation": "203", "volcanoSubregion": "Alaska (western)", "volcanoLongitude": "-170.3"},
                       "INGAKSLUGWAT HILLS": {"volcanoNumber": "314030", "volcanoLatitude": "61.43", "volcanoElevation": "190", "volcanoSubregion": "Alaska (western)", "volcanoLongitude": "-164.47"},
                       "ST. MICHAEL": {"volcanoNumber": "314040", "volcanoLatitude": "63.45", "volcanoElevation": "715", "volcanoSubregion": "Alaska (western)", "volcanoLongitude": "-162.12"},
                       "IMURUK LAKE": {"volcanoNumber": "314060", "volcanoLatitude": "65.517", "volcanoElevation": "610", "volcanoSubregion": "Alaska (western)", "volcanoLongitude": "-163.45"},
                       "BUZZARD CREEK": {"volcanoNumber": "315001", "volcanoLatitude": "64.062", "volcanoElevation": "830", "volcanoSubregion": "Alaska (eastern)", "volcanoLongitude": "-148.433"},
                       "WRANGELL": {"volcanoNumber": "315020", "volcanoLatitude": "62.006", "volcanoElevation": "4278", "volcanoSubregion": "Alaska (eastern)", "volcanoLongitude": "-144.017"},
                       "CHURCHILL": {"volcanoNumber": "315030", "volcanoLatitude": "61.38", "volcanoElevation": "5005", "volcanoSubregion": "Alaska (eastern)", "volcanoLongitude": "-141.75"},
                       "EDGECUMBE": {"volcanoNumber": "315040", "volcanoLatitude": "57.05", "volcanoElevation": "970", "volcanoSubregion": "Alaska (eastern)", "volcanoLongitude": "-135.75"},
                       "DUNCAN CANAL": {"volcanoNumber": "315050", "volcanoLatitude": "56.5", "volcanoElevation": "15", "volcanoSubregion": "Alaska (eastern)", "volcanoLongitude": "-133.1"},
                       "TLEVAK STRAIT-SUEMEZ IS.": {"volcanoNumber": "315060", "volcanoLatitude": "55.25", "volcanoElevation": "50", "volcanoSubregion": "Alaska (eastern)", "volcanoLongitude": "-133.3"},
                       "BEHM CANAL-RUDYERD BAY": {"volcanoNumber": "315070", "volcanoLatitude": "55.32", "volcanoElevation": "500", "volcanoSubregion": "Alaska (eastern)", "volcanoLongitude": "-131.05"},
                       "BAKER": {"volcanoNumber": "321010", "volcanoLatitude": "48.777", "volcanoElevation": "3285", "volcanoSubregion": "USA (Washington)", "volcanoLongitude": "-121.813"},
                       "GLACIER PEAK": {"volcanoNumber": "321020", "volcanoLatitude": "48.112", "volcanoElevation": "3213", "volcanoSubregion": "USA (Washington)", "volcanoLongitude": "-121.113"},
                       "RAINIER": {"volcanoNumber": "321030", "volcanoLatitude": "46.853", "volcanoElevation": "4392", "volcanoSubregion": "USA (Washington)", "volcanoLongitude": "-121.76"},
                       "ADAMS": {"volcanoNumber": "321040", "volcanoLatitude": "46.206", "volcanoElevation": "3742", "volcanoSubregion": "USA (Washington)", "volcanoLongitude": "-121.49"},
                       "ST. HELENS": {"volcanoNumber": "321050", "volcanoLatitude": "46.2", "volcanoElevation": "2549", "volcanoSubregion": "USA (Washington)", "volcanoLongitude": "-122.18"},
                       "WEST CRATER": {"volcanoNumber": "321060", "volcanoLatitude": "45.88", "volcanoElevation": "1329", "volcanoSubregion": "USA (Washington)", "volcanoLongitude": "-122.08"},
                       "INDIAN HEAVEN": {"volcanoNumber": "321070", "volcanoLatitude": "45.93", "volcanoElevation": "1806", "volcanoSubregion": "USA (Washington)", "volcanoLongitude": "-121.82"},
                       "HOOD": {"volcanoNumber": "322010", "volcanoLatitude": "45.374", "volcanoElevation": "3426", "volcanoSubregion": "USA (Oregon)", "volcanoLongitude": "-121.695"},
                       "JEFFERSON": {"volcanoNumber": "322020", "volcanoLatitude": "44.674", "volcanoElevation": "3199", "volcanoSubregion": "USA (Oregon)", "volcanoLongitude": "-121.8"},
                       "BLUE LAKE CRATER": {"volcanoNumber": "322030", "volcanoLatitude": "44.411", "volcanoElevation": "1230", "volcanoSubregion": "USA (Oregon)", "volcanoLongitude": "-121.774"},
                       "SAND MOUNTAIN FIELD": {"volcanoNumber": "322040", "volcanoLatitude": "44.38", "volcanoElevation": "1664", "volcanoSubregion": "USA (Oregon)", "volcanoLongitude": "-121.93"},
                       "BELKNAP": {"volcanoNumber": "322060", "volcanoLatitude": "44.285", "volcanoElevation": "2095", "volcanoSubregion": "USA (Oregon)", "volcanoLongitude": "-121.841"},
                       "THREE SISTERS": {"volcanoNumber": "322070", "volcanoLatitude": "44.133", "volcanoElevation": "3159", "volcanoSubregion": "USA (Oregon)", "volcanoLongitude": "-121.767"},
                       "BACHELOR": {"volcanoNumber": "322090", "volcanoLatitude": "43.979", "volcanoElevation": "2763", "volcanoSubregion": "USA (Oregon)", "volcanoLongitude": "-121.688"},
                       "DAVIS LAKE": {"volcanoNumber": "322100", "volcanoLatitude": "43.57", "volcanoElevation": "2163", "volcanoSubregion": "USA (Oregon)", "volcanoLongitude": "-121.82"},
                       "NEWBERRY": {"volcanoNumber": "322110", "volcanoLatitude": "43.722", "volcanoElevation": "2434", "volcanoSubregion": "USA (Oregon)", "volcanoLongitude": "-121.229"},
                       "DEVILS GARDEN": {"volcanoNumber": "322120", "volcanoLatitude": "43.512", "volcanoElevation": "1698", "volcanoSubregion": "USA (Oregon)", "volcanoLongitude": "-120.861"},
                       "CINNAMON BUTTE": {"volcanoNumber": "322150", "volcanoLatitude": "43.241", "volcanoElevation": "1956", "volcanoSubregion": "USA (Oregon)", "volcanoLongitude": "-122.108"},
                       "CRATER LAKE": {"volcanoNumber": "322160", "volcanoLatitude": "42.93", "volcanoElevation": "2487", "volcanoSubregion": "USA (Oregon)", "volcanoLongitude": "-122.12"},
                       "DIAMOND CRATERS": {"volcanoNumber": "322170", "volcanoLatitude": "43.1", "volcanoElevation": "1435", "volcanoSubregion": "USA (Oregon)", "volcanoLongitude": "-118.75"},
                       "JORDAN CRATERS": {"volcanoNumber": "322190", "volcanoLatitude": "43.147", "volcanoElevation": "1473", "volcanoSubregion": "USA (Oregon)", "volcanoLongitude": "-117.46"},
                       "SHASTA": {"volcanoNumber": "323010", "volcanoLatitude": "41.409", "volcanoElevation": "4317", "volcanoSubregion": "USA (California)", "volcanoLongitude": "-122.193"},
                       "MEDICINE LAKE": {"volcanoNumber": "323020", "volcanoLatitude": "41.611", "volcanoElevation": "2412", "volcanoSubregion": "USA (California)", "volcanoLongitude": "-121.554"},
                       "LASSEN VOLCANIC CENTER": {"volcanoNumber": "323080", "volcanoLatitude": "40.492", "volcanoElevation": "3187", "volcanoSubregion": "USA (California)", "volcanoLongitude": "-121.508"},
                       "CLEAR LAKE": {"volcanoNumber": "323100", "volcanoLatitude": "38.97", "volcanoElevation": "1439", "volcanoSubregion": "USA (California)", "volcanoLongitude": "-122.77"},
                       "MONO LAKE VOLCANIC FIELD": {"volcanoNumber": "323110", "volcanoLatitude": "38", "volcanoElevation": "2121", "volcanoSubregion": "USA (California)", "volcanoLongitude": "-119.03"},
                       "MONO CRATERS": {"volcanoNumber": "323120", "volcanoLatitude": "37.88", "volcanoElevation": "2796", "volcanoSubregion": "USA (California)", "volcanoLongitude": "-119"},
                       "INYO CRATERS": {"volcanoNumber": "323130", "volcanoLatitude": "37.692", "volcanoElevation": "2629", "volcanoSubregion": "USA (California)", "volcanoLongitude": "-119.02"},
                       "MAMMOTH MOUNTAIN": {"volcanoNumber": "323150", "volcanoLatitude": "37.631", "volcanoElevation": "3369", "volcanoSubregion": "USA (California)", "volcanoLongitude": "-119.032"},
                       "UBEHEBE CRATERS": {"volcanoNumber": "323160", "volcanoLatitude": "37.02", "volcanoElevation": "752", "volcanoSubregion": "USA (California)", "volcanoLongitude": "-117.45"},
                       "GOLDEN TROUT CREEK": {"volcanoNumber": "323170", "volcanoLatitude": "36.358", "volcanoElevation": "2886", "volcanoSubregion": "USA (California)", "volcanoLongitude": "-118.32"},
                       "COSO VOLCANIC FIELD": {"volcanoNumber": "323180", "volcanoLatitude": "36.03", "volcanoElevation": "2400", "volcanoSubregion": "USA (California)", "volcanoLongitude": "-117.82"},
                       "LAVIC LAKE": {"volcanoNumber": "323190", "volcanoLatitude": "34.75", "volcanoElevation": "1495", "volcanoSubregion": "USA (California)", "volcanoLongitude": "-116.625"},
                       "SALTON BUTTES": {"volcanoNumber": "323200", "volcanoLatitude": "33.197", "volcanoElevation": "-40", "volcanoSubregion": "USA (California)", "volcanoLongitude": "-115.616"},
                       "LONG VALLEY": {"volcanoNumber": "323822", "volcanoLatitude": "37.7", "volcanoElevation": "3390", "volcanoSubregion": "USA (California)", "volcanoLongitude": "-118.87"},
                       "BLACK BUTTE CRATER LAVA FIELD": {"volcanoNumber": "324010", "volcanoLatitude": "43.183", "volcanoElevation": "1478", "volcanoSubregion": "USA (Idaho)", "volcanoLongitude": "-114.352"},
                       "CRATERS OF THE MOON": {"volcanoNumber": "324020", "volcanoLatitude": "43.42", "volcanoElevation": "2005", "volcanoSubregion": "USA (Idaho)", "volcanoLongitude": "-113.5"},
                       "WAPI LAVA FIELD": {"volcanoNumber": "324030", "volcanoLatitude": "42.88", "volcanoElevation": "1604", "volcanoSubregion": "USA (Idaho)", "volcanoLongitude": "-113.22"},
                       "HELLS HALF ACRE": {"volcanoNumber": "324040", "volcanoLatitude": "43.5", "volcanoElevation": "1631", "volcanoSubregion": "USA (Idaho)", "volcanoLongitude": "-112.45"},
                       "YELLOWSTONE": {"volcanoNumber": "325010", "volcanoLatitude": "44.43", "volcanoElevation": "2805", "volcanoSubregion": "USA (Wyoming)", "volcanoLongitude": "-110.67"},
                       "SODA LAKES": {"volcanoNumber": "326010", "volcanoLatitude": "39.53", "volcanoElevation": "1251", "volcanoSubregion": "USA (Nevada)", "volcanoLongitude": "-118.87"},
                       "STEAMBOAT SPRINGS": {"volcanoNumber": "326801", "volcanoLatitude": "39.375", "volcanoElevation": "1415", "volcanoSubregion": "USA (Nevada)", "volcanoLongitude": "-119.72"},
                       "MARKAGUNT PLATEAU": {"volcanoNumber": "327040", "volcanoLatitude": "37.58", "volcanoElevation": "2840", "volcanoSubregion": "USA (Utah)", "volcanoLongitude": "-112.67"},
                       "BLACK ROCK DESERT": {"volcanoNumber": "327050", "volcanoLatitude": "38.97", "volcanoElevation": "1800", "volcanoSubregion": "USA (Utah)", "volcanoLongitude": "-112.5"},
                       "CARRIZOZO": {"volcanoNumber": "327110", "volcanoLatitude": "33.78", "volcanoElevation": "1731", "volcanoSubregion": "USA (New Mexico)", "volcanoLongitude": "-105.93"},
                       "ZUNI-BANDERA": {"volcanoNumber": "327120", "volcanoLatitude": "34.8", "volcanoElevation": "2550", "volcanoSubregion": "USA (New Mexico)", "volcanoLongitude": "-108"},
                       "VALLES CALDERA": {"volcanoNumber": "327817", "volcanoLatitude": "35.87", "volcanoElevation": "3430", "volcanoSubregion": "USA (New Mexico)", "volcanoLongitude": "-106.57"},
                       "DOTSERO": {"volcanoNumber": "328010", "volcanoLatitude": "39.661", "volcanoElevation": "2230", "volcanoSubregion": "USA (Colorado)", "volcanoLongitude": "-107.035"},
                       "UINKARET FIELD": {"volcanoNumber": "329010", "volcanoLatitude": "36.38", "volcanoElevation": "1555", "volcanoSubregion": "USA (Arizona)", "volcanoLongitude": "-113.13"},
                       "SAN FRANCISCO VOLCANIC FIELD": {"volcanoNumber": "329020", "volcanoLatitude": "35.347", "volcanoElevation": "3850", "volcanoSubregion": "USA (Arizona)", "volcanoLongitude": "-111.678"},
                       "LOIHI": {"volcanoNumber": "332000", "volcanoLatitude": "18.92", "volcanoElevation": "-975", "volcanoSubregion": "Hawaiian Islands", "volcanoLongitude": "-155.27"},
                       "KILAUEA": {"volcanoNumber": "332010", "volcanoLatitude": "19.421", "volcanoElevation": "1222", "volcanoSubregion": "Hawaiian Islands", "volcanoLongitude": "-155.287"},
                       "MAUNA LOA": {"volcanoNumber": "332020", "volcanoLatitude": "19.475", "volcanoElevation": "4170", "volcanoSubregion": "Hawaiian Islands", "volcanoLongitude": "-155.608"},
                       "MAUNA KEA": {"volcanoNumber": "332030", "volcanoLatitude": "19.82", "volcanoElevation": "4205", "volcanoSubregion": "Hawaiian Islands", "volcanoLongitude": "-155.47"},
                       "HUALALAI": {"volcanoNumber": "332040", "volcanoLatitude": "19.692", "volcanoElevation": "2523", "volcanoSubregion": "Hawaiian Islands", "volcanoLongitude": "-155.87"},
                       "HALEAKALA": {"volcanoNumber": "332060", "volcanoLatitude": "20.708", "volcanoElevation": "3055", "volcanoSubregion": "Hawaiian Islands", "volcanoLongitude": "-156.25"}
                       }
        return volcanoDict